<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-08-27">
<meta name="description" content="Gamma GLM for severity and Poisson GLM for frequency — the actuarial industry standard and interpretable baseline.">

<title>GLM: Gamma and Poisson Baselines – Insurance Claims Predictor</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-b85bc7c33db8c58e0ec93c3465666fed.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-3a0730cdd9a625ae55dc35d4063f4b4c.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed fullcontent quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Insurance Claims Predictor</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../notebooks.html"> 
<span class="menu-text">Notebooks</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/dpark2380/Insurance-Claims-Predictor"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">GLM: Gamma and Poisson Baselines</h1>
                  <div>
        <div class="description">
          Gamma GLM for severity and Poisson GLM for frequency — the actuarial industry standard and interpretable baseline.
        </div>
      </div>
                </div>
  </div>
    
  
  <div class="quarto-title-meta">

      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">August 27, 2026</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<section id="notebook-2-glm-models" class="level1">
<h1>Notebook 2: GLM Models</h1>
<p>This notebook fits two GLMs. - <strong>Part 1 — Severity:</strong> Gamma GLM with log-link, predicting claim amount given a claim occurred - <strong>Part 2 — Frequency:</strong> Poisson GLM with log-link, predicting claim rate across all policies</p>
<p>The outputs of both models are combined in notebook 5 to estimate a pure premium.</p>
<div id="2" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;execution&quot;,&quot;value&quot;:{&quot;iopub.execute_input&quot;:&quot;2026-08-27T15:19:29.718516Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-08-27T15:19:29.718343Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-08-27T15:19:30.887036Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-08-27T15:19:30.886556Z&quot;}}" data-execution_count="1">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.model_selection <span class="im">import</span> train_test_split</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.metrics <span class="im">import</span> mean_absolute_error, mean_squared_error</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.api <span class="im">as</span> sm</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> warnings</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>warnings.filterwarnings(<span class="st">'ignore'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<hr>
<section id="part-1-severity-gamma-glm" class="level2">
<h2 class="anchored" data-anchor-id="part-1-severity-gamma-glm">Part 1: Severity — Gamma GLM</h2>
<p><em>Predicts how much a claim costs, given one occurred. Uses 26k claims dataset.</em></p>
<div id="4" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;execution&quot;,&quot;value&quot;:{&quot;iopub.execute_input&quot;:&quot;2026-08-27T15:19:30.888195Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-08-27T15:19:30.888087Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-08-27T15:19:30.903204Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-08-27T15:19:30.902871Z&quot;}}" data-execution_count="2">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.read_csv(<span class="st">'../data/claims_cleaned.csv'</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(df.shape)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>df.head()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>(26439, 13)</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="2">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">IDpol</th>
<th data-quarto-table-cell-role="th">ClaimNb</th>
<th data-quarto-table-cell-role="th">Exposure</th>
<th data-quarto-table-cell-role="th">Area</th>
<th data-quarto-table-cell-role="th">VehPower</th>
<th data-quarto-table-cell-role="th">VehAge</th>
<th data-quarto-table-cell-role="th">DrivAge</th>
<th data-quarto-table-cell-role="th">BonusMalus</th>
<th data-quarto-table-cell-role="th">VehBrand</th>
<th data-quarto-table-cell-role="th">VehGas</th>
<th data-quarto-table-cell-role="th">Density</th>
<th data-quarto-table-cell-role="th">Region</th>
<th data-quarto-table-cell-role="th">ClaimAmount</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>139.0</td>
<td>1</td>
<td>0.75</td>
<td>F</td>
<td>7</td>
<td>1</td>
<td>61</td>
<td>50</td>
<td>B12</td>
<td>'Regular'</td>
<td>27000</td>
<td>R11</td>
<td>303.00</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>190.0</td>
<td>1</td>
<td>0.14</td>
<td>B</td>
<td>12</td>
<td>5</td>
<td>50</td>
<td>60</td>
<td>B12</td>
<td>'Diesel'</td>
<td>56</td>
<td>R25</td>
<td>1981.84</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>414.0</td>
<td>1</td>
<td>0.14</td>
<td>E</td>
<td>4</td>
<td>0</td>
<td>36</td>
<td>85</td>
<td>B12</td>
<td>'Regular'</td>
<td>4792</td>
<td>R11</td>
<td>1456.55</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>424.0</td>
<td>2</td>
<td>0.62</td>
<td>F</td>
<td>10</td>
<td>0</td>
<td>51</td>
<td>100</td>
<td>B12</td>
<td>'Regular'</td>
<td>27000</td>
<td>R11</td>
<td>989.64</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>424.0</td>
<td>2</td>
<td>0.62</td>
<td>F</td>
<td>10</td>
<td>0</td>
<td>51</td>
<td>100</td>
<td>B12</td>
<td>'Regular'</td>
<td>27000</td>
<td>R11</td>
<td>9844.36</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="5" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;execution&quot;,&quot;value&quot;:{&quot;iopub.execute_input&quot;:&quot;2026-08-27T15:19:30.904201Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-08-27T15:19:30.904145Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-08-27T15:19:30.910581Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-08-27T15:19:30.910281Z&quot;}}" data-execution_count="3">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Features to use — drop IDpol (ID), Exposure and ClaimNb (not relevant for severity)</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>features <span class="op">=</span> [<span class="st">'VehPower'</span>, <span class="st">'VehAge'</span>, <span class="st">'DrivAge'</span>, <span class="st">'BonusMalus'</span>, <span class="st">'Density'</span>, <span class="st">'Area'</span>, <span class="st">'VehBrand'</span>, <span class="st">'VehGas'</span>, <span class="st">'Region'</span>]</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>target <span class="op">=</span> <span class="st">'ClaimAmount'</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Changing the categorical columns: Area, VehBrand, VehGas, Region into numeric columns</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Hint: use pd.get_dummies with drop_first=True</span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a><span class="co"># df[features + [target]] -&gt; subsetting to only the features and the target variable.</span></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>df_model <span class="op">=</span> pd.get_dummies(df[features <span class="op">+</span> [target]], columns<span class="op">=</span>[<span class="st">'Area'</span>, <span class="st">'VehBrand'</span>, <span class="st">'VehGas'</span>, <span class="st">'Region'</span>], drop_first<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>df_model <span class="op">=</span> df_model.astype(<span class="bu">float</span>)</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Features after encoding: </span><span class="sc">{</span>df_model<span class="sc">.</span>shape[<span class="dv">1</span>] <span class="op">-</span> <span class="dv">1</span><span class="sc">}</span><span class="ss">'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Features after encoding: 42</code></pre>
</div>
</div>
<div id="6" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;execution&quot;,&quot;value&quot;:{&quot;iopub.execute_input&quot;:&quot;2026-08-27T15:19:30.911412Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-08-27T15:19:30.911353Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-08-27T15:19:30.916732Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-08-27T15:19:30.916403Z&quot;}}" data-execution_count="4">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> df_model.drop(columns<span class="op">=</span>[target])</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> df_model[target]</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Split into train/test sets (80/20, random_state=42)</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a><span class="co"># random_state must match notebooks 03/04/05 so all three severity models are</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a><span class="co"># trained and evaluated on identical rows — otherwise the comparison in</span></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a><span class="co"># notebook 05 is apples-to-oranges.</span></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>X_train, X_test, y_train, y_test <span class="op">=</span> train_test_split(X, y, test_size<span class="op">=</span><span class="fl">0.2</span>, random_state<span class="op">=</span><span class="dv">42</span>)</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Train: </span><span class="sc">{</span>X_train<span class="sc">.</span>shape<span class="sc">}</span><span class="ss">, Test: </span><span class="sc">{</span>X_test<span class="sc">.</span>shape<span class="sc">}</span><span class="ss">'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Train: (21151, 42), Test: (5288, 42)</code></pre>
</div>
</div>
</section>
<section id="fit-gamma-glm" class="level2">
<h2 class="anchored" data-anchor-id="fit-gamma-glm">2. Fit Gamma GLM</h2>
<p>Using <code>statsmodels</code> which gives full statistical output (p-values, confidence intervals).</p>
<p>Gamma — the distribution we assume for ClaimAmount. We use it because. - Claims are always positive (can’t have a negative claim) - The distribution is right-skewed, which Gamma handles naturally<br>
- Errors are proportional — a €500 error on a €1,000 claim is worse than a €500 error on a €10,000 claim. Gamma captures this.</p>
<p>Log-link — the function connecting the features to the prediction. We use it because. - It ensures predictions are always positive (you can’t predict a negative claim amount)<br>
- It means the model is multiplicative — each feature multiplies the expected claim by some factor, which makes<br>
actuarial sense (e.g.&nbsp;a high-power vehicle multiplies your expected claim by 1.1x)</p>
<p>The alternative would be plain linear regression, which assumes normally distributed errors and can predict negative values — neither of which makes sense for insurance claims.</p>
<div id="8" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;execution&quot;,&quot;value&quot;:{&quot;iopub.execute_input&quot;:&quot;2026-08-27T15:19:30.917791Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-08-27T15:19:30.917740Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-08-27T15:19:31.048759Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-08-27T15:19:31.048383Z&quot;}}" data-execution_count="5">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># adding an intercept column to ensure the model doesn't simply pass through the origin.</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>X_train_sm <span class="op">=</span> sm.add_constant(X_train)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>X_test_sm  <span class="op">=</span> sm.add_constant(X_test)</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a><span class="co"># </span><span class="al">TODO</span><span class="co">: fit a Gamma GLM with log-link using sm.GLM</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Hint: family=sm.families.Gamma(link=sm.families.links.Log())</span></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>gamma_log_model <span class="op">=</span> sm.GLM(y_train, X_train_sm, family<span class="op">=</span>sm.families.Gamma(link<span class="op">=</span>sm.families.links.Log()))</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Result is the gamma log model.</span></span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>result <span class="op">=</span> gamma_log_model.fit()</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(result.summary())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                 Generalized Linear Model Regression Results                  
==============================================================================
Dep. Variable:            ClaimAmount   No. Observations:                21151
Model:                            GLM   Df Residuals:                    21108
Model Family:                   Gamma   Df Model:                           42
Link Function:                    Log   Scale:                          1.9320
Method:                          IRLS   Log-Likelihood:            -1.7986e+05
Date:                Fri, 28 Aug 2026   Deviance:                       21655.
Time:                        01:19:31   Pearson chi2:                 4.08e+04
No. Iterations:                    13   Pseudo R-squ. (CS):           0.006939
Covariance Type:            nonrobust                                         
====================================================================================
                       coef    std err          z      P&gt;|z|      [0.025      0.975]
------------------------------------------------------------------------------------
const                7.0577      0.086     82.019      0.000       6.889       7.226
VehPower             0.0094      0.005      1.849      0.064      -0.001       0.019
VehAge              -0.0085      0.002     -4.139      0.000      -0.013      -0.004
DrivAge              0.0008      0.001      1.092      0.275      -0.001       0.002
BonusMalus           0.0030      0.001      5.499      0.000       0.002       0.004
Density           4.017e-06   6.62e-06      0.607      0.544   -8.95e-06     1.7e-05
Area_B               0.0106      0.041      0.259      0.796      -0.069       0.091
Area_C              -0.0393      0.034     -1.163      0.245      -0.106       0.027
Area_D              -0.0200      0.036     -0.556      0.578      -0.090       0.050
Area_E            2.908e-05      0.047      0.001      1.000      -0.091       0.091
Area_F              -0.2364      0.161     -1.468      0.142      -0.552       0.079
VehBrand_B10         0.0979      0.061      1.608      0.108      -0.021       0.217
VehBrand_B11         0.0946      0.066      1.431      0.152      -0.035       0.224
VehBrand_B12         0.0308      0.034      0.905      0.365      -0.036       0.097
VehBrand_B13         0.0348      0.070      0.498      0.619      -0.102       0.172
VehBrand_B14        -0.1980      0.144     -1.375      0.169      -0.480       0.084
VehBrand_B2          0.0171      0.027      0.642      0.521      -0.035       0.069
VehBrand_B3         -0.0036      0.037     -0.097      0.922      -0.076       0.069
VehBrand_B4         -0.0572      0.051     -1.115      0.265      -0.158       0.043
VehBrand_B5         -0.0219      0.043     -0.514      0.607      -0.106       0.062
VehBrand_B6         -0.0270      0.048     -0.560      0.575      -0.121       0.067
VehGas_'Regular'    -0.0007      0.020     -0.037      0.971      -0.040       0.038
Region_R21           0.2164      0.185      1.167      0.243      -0.147       0.580
Region_R22          -0.0417      0.096     -0.433      0.665      -0.230       0.147
Region_R23          -0.0461      0.113     -0.407      0.684      -0.268       0.176
Region_R24           0.0395      0.045      0.872      0.383      -0.049       0.128
Region_R25           0.0109      0.082      0.133      0.894      -0.150       0.171
Region_R26           0.1320      0.095      1.386      0.166      -0.055       0.319
Region_R31           0.0817      0.063      1.292      0.196      -0.042       0.206
Region_R41           0.2370      0.082      2.902      0.004       0.077       0.397
Region_R42          -0.1799      0.168     -1.070      0.285      -0.509       0.150
Region_R43           0.2777      0.257      1.081      0.280      -0.226       0.781
Region_R52           0.0111      0.055      0.200      0.841      -0.097       0.120
Region_R53           0.0600      0.054      1.118      0.263      -0.045       0.165
Region_R54           0.0300      0.068      0.439      0.660      -0.104       0.164
Region_R72           0.0762      0.062      1.232      0.218      -0.045       0.198
Region_R73           0.0232      0.090      0.259      0.796      -0.152       0.199
Region_R74          -0.1146      0.118     -0.974      0.330      -0.345       0.116
Region_R82           0.0516      0.045      1.155      0.248      -0.036       0.139
Region_R83          -0.1520      0.136     -1.118      0.264      -0.419       0.115
Region_R91           0.2112      0.062      3.412      0.001       0.090       0.333
Region_R93           0.2212      0.047      4.709      0.000       0.129       0.313
Region_R94           0.2910      0.145      2.010      0.044       0.007       0.575
====================================================================================</code></pre>
</div>
</div>
</section>
<section id="evaluate-on-test-set" class="level2">
<h2 class="anchored" data-anchor-id="evaluate-on-test-set">3. Evaluate on Test Set</h2>
<div id="10" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;execution&quot;,&quot;value&quot;:{&quot;iopub.execute_input&quot;:&quot;2026-08-27T15:19:31.049744Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-08-27T15:19:31.049683Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-08-27T15:19:31.054170Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-08-27T15:19:31.053872Z&quot;}}" data-execution_count="6">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>y_pred <span class="op">=</span> result.predict(X_test_sm)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>mae  <span class="op">=</span> mean_absolute_error(y_test, y_pred)</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>rmse <span class="op">=</span> mean_squared_error(y_test, y_pred) <span class="op">**</span> <span class="fl">0.5</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Gamma deviance — the actuarially correct metric for severity models.</span></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Penalises proportional errors rather than absolute ones, which is what matters</span></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a><span class="co"># when claim sizes span three orders of magnitude.</span></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> gamma_deviance(y_true, y_pred):</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="dv">2</span> <span class="op">*</span> np.mean((y_true <span class="op">-</span> y_pred) <span class="op">/</span> y_pred <span class="op">-</span> np.log(y_true <span class="op">/</span> y_pred))</span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>gd <span class="op">=</span> gamma_deviance(y_test.values, y_pred.values)</span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'--- GLM Test Set Performance ---'</span>)</span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'MAE:             </span><span class="sc">{</span>mae<span class="sc">:,.2f}</span><span class="ss">'</span>)</span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'RMSE:            </span><span class="sc">{</span>rmse<span class="sc">:,.2f}</span><span class="ss">'</span>)</span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Gamma Deviance:  </span><span class="sc">{</span>gd<span class="sc">:.4f}</span><span class="ss">'</span>)</span>
<span id="cb10-18"><a href="#cb10-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-19"><a href="#cb10-19" aria-hidden="true" tabindex="-1"></a><span class="co"># ── How much signal is actually in the features? ─────────────────────────────</span></span>
<span id="cb10-20"><a href="#cb10-20" aria-hidden="true" tabindex="-1"></a><span class="co"># A model's absolute error means little on its own — the benchmark is what you</span></span>
<span id="cb10-21"><a href="#cb10-21" aria-hidden="true" tabindex="-1"></a><span class="co"># get by ignoring the features entirely and predicting the training mean for</span></span>
<span id="cb10-22"><a href="#cb10-22" aria-hidden="true" tabindex="-1"></a><span class="co"># every claim. Deviance explained (a pseudo-R^2) is the in-sample version of the</span></span>
<span id="cb10-23"><a href="#cb10-23" aria-hidden="true" tabindex="-1"></a><span class="co"># same question: how much of the null model's deviance did the features remove?</span></span>
<span id="cb10-24"><a href="#cb10-24" aria-hidden="true" tabindex="-1"></a>pseudo_r2 <span class="op">=</span> <span class="dv">1</span> <span class="op">-</span> result.deviance <span class="op">/</span> result.null_deviance</span>
<span id="cb10-25"><a href="#cb10-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-26"><a href="#cb10-26" aria-hidden="true" tabindex="-1"></a>baseline  <span class="op">=</span> np.full(<span class="bu">len</span>(y_test), y_train.mean())</span>
<span id="cb10-27"><a href="#cb10-27" aria-hidden="true" tabindex="-1"></a>gd_base   <span class="op">=</span> gamma_deviance(y_test.values, baseline)</span>
<span id="cb10-28"><a href="#cb10-28" aria-hidden="true" tabindex="-1"></a>mae_base  <span class="op">=</span> mean_absolute_error(y_test, baseline)</span>
<span id="cb10-29"><a href="#cb10-29" aria-hidden="true" tabindex="-1"></a>rmse_base <span class="op">=</span> mean_squared_error(y_test, baseline) <span class="op">**</span> <span class="fl">0.5</span></span>
<span id="cb10-30"><a href="#cb10-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-31"><a href="#cb10-31" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'</span><span class="ch">\n</span><span class="ss">--- Against an intercept-only baseline (predict the mean for everyone) ---'</span>)</span>
<span id="cb10-32"><a href="#cb10-32" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Deviance explained (train):  </span><span class="sc">{</span>pseudo_r2<span class="sc">:.2%}</span><span class="ss">'</span>)</span>
<span id="cb10-33"><a href="#cb10-33" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'</span><span class="sc">{</span><span class="st">""</span><span class="sc">:18}</span><span class="ss"> </span><span class="sc">{</span><span class="st">"baseline"</span><span class="sc">:&gt;12}</span><span class="ss"> </span><span class="sc">{</span><span class="st">"model"</span><span class="sc">:&gt;12}</span><span class="ss">'</span>)</span>
<span id="cb10-34"><a href="#cb10-34" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'</span><span class="sc">{</span><span class="st">"Gamma Deviance"</span><span class="sc">:18}</span><span class="ss"> </span><span class="sc">{</span>gd_base<span class="sc">:&gt;12.4f}</span><span class="ss"> </span><span class="sc">{</span>gd<span class="sc">:&gt;12.4f}</span><span class="ss">'</span>)</span>
<span id="cb10-35"><a href="#cb10-35" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'</span><span class="sc">{</span><span class="st">"MAE"</span><span class="sc">:18}</span><span class="ss"> </span><span class="sc">{</span>mae_base<span class="sc">:&gt;12,.2f}</span><span class="ss"> </span><span class="sc">{</span>mae<span class="sc">:&gt;12,.2f}</span><span class="ss">'</span>)</span>
<span id="cb10-36"><a href="#cb10-36" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'</span><span class="sc">{</span><span class="st">"RMSE"</span><span class="sc">:18}</span><span class="ss"> </span><span class="sc">{</span>rmse_base<span class="sc">:&gt;12,.2f}</span><span class="ss"> </span><span class="sc">{</span>rmse<span class="sc">:&gt;12,.2f}</span><span class="ss">'</span>)</span>
<span id="cb10-37"><a href="#cb10-37" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'</span><span class="ch">\n</span><span class="ss">Prediction spread: </span><span class="sc">{</span>y_pred<span class="sc">.</span><span class="bu">min</span>()<span class="sc">:,.0f}</span><span class="ss"> to </span><span class="sc">{</span>y_pred<span class="sc">.</span><span class="bu">max</span>()<span class="sc">:,.0f}</span><span class="ss"> EUR '</span></span>
<span id="cb10-38"><a href="#cb10-38" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f'(</span><span class="sc">{</span>y_pred<span class="sc">.</span><span class="bu">max</span>()<span class="op">/</span>y_pred<span class="sc">.</span><span class="bu">min</span>()<span class="sc">:.2f}</span><span class="ss">x), vs actuals </span><span class="sc">{</span>y_test<span class="sc">.</span><span class="bu">min</span>()<span class="sc">:,.0f}</span><span class="ss"> to </span><span class="sc">{</span>y_test<span class="sc">.</span><span class="bu">max</span>()<span class="sc">:,.0f}</span><span class="ss">.'</span>)</span>
<span id="cb10-39"><a href="#cb10-39" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'corr(actual, predicted) = </span><span class="sc">{</span>np<span class="sc">.</span>corrcoef(y_test, y_pred)[<span class="dv">0</span>,<span class="dv">1</span>]<span class="sc">:.4f}</span><span class="ss">'</span>)</span>
<span id="cb10-40"><a href="#cb10-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-41"><a href="#cb10-41" aria-hidden="true" tabindex="-1"></a><span class="co"># Save for final comparison</span></span>
<span id="cb10-42"><a href="#cb10-42" aria-hidden="true" tabindex="-1"></a>glm_metrics <span class="op">=</span> {<span class="st">'model'</span>: <span class="st">'GLM'</span>, <span class="st">'MAE'</span>: mae, <span class="st">'RMSE'</span>: rmse, <span class="st">'GammaDeviance'</span>: gd}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>--- GLM Test Set Performance ---
MAE:             1,102.26
RMSE:            2,261.57
Gamma Deviance:  1.0595

--- Against an intercept-only baseline (predict the mean for everyone) ---
Deviance explained (train):  1.30%
                       baseline        model
Gamma Deviance           1.0642       1.0595
MAE                    1,104.71     1,102.26
RMSE                   2,263.58     2,261.57

Prediction spread: 873 to 2,506 EUR (2.87x), vs actuals 1 to 16,451.
corr(actual, predicted) = 0.0522</code></pre>
</div>
</div>
</section>
<section id="visualise-predictions-vs-actuals" class="level2">
<h2 class="anchored" data-anchor-id="visualise-predictions-vs-actuals">4. Visualise Predictions vs Actuals</h2>
<div id="12" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;execution&quot;,&quot;value&quot;:{&quot;iopub.execute_input&quot;:&quot;2026-08-27T15:19:31.055140Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-08-27T15:19:31.055077Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-08-27T15:19:31.348415Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-08-27T15:19:31.348001Z&quot;}}" data-execution_count="7">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Three panels, because the obvious plot is the least informative one here.</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">3</span>, figsize<span class="op">=</span>(<span class="dv">18</span>, <span class="dv">5</span>))</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="co"># ── Panel 1: calibration by predicted decile — the diagnostic that matters ───</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="co"># A Gamma GLM estimates the conditional MEAN E[Y|X], not the realisation Y. So</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a><span class="co"># the honest test is not "does each point sit on the diagonal" but "within a</span></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a><span class="co"># group of policies the model scored alike, does the average claim match the</span></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a><span class="co"># average prediction?" That is what this panel asks.</span></span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>cal <span class="op">=</span> pd.DataFrame({<span class="st">'actual'</span>: y_test.values, <span class="st">'pred'</span>: y_pred.values})</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>cal[<span class="st">'decile'</span>] <span class="op">=</span> pd.qcut(cal[<span class="st">'pred'</span>], <span class="dv">10</span>, labels<span class="op">=</span><span class="va">False</span>, duplicates<span class="op">=</span><span class="st">'drop'</span>) <span class="op">+</span> <span class="dv">1</span></span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>cal_g <span class="op">=</span> cal.groupby(<span class="st">'decile'</span>).agg(mean_pred<span class="op">=</span>(<span class="st">'pred'</span>, <span class="st">'mean'</span>),</span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a>                                  mean_actual<span class="op">=</span>(<span class="st">'actual'</span>, <span class="st">'mean'</span>),</span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a>                                  n<span class="op">=</span>(<span class="st">'actual'</span>, <span class="st">'size'</span>))</span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].plot(cal_g[<span class="st">'mean_pred'</span>], cal_g[<span class="st">'mean_actual'</span>], <span class="st">'o-'</span>, color<span class="op">=</span><span class="st">'#4C72B0'</span>, label<span class="op">=</span><span class="st">'Observed'</span>)</span>
<span id="cb12-16"><a href="#cb12-16" aria-hidden="true" tabindex="-1"></a>lim <span class="op">=</span> [<span class="bu">min</span>(cal_g.<span class="bu">min</span>().iloc[:<span class="dv">2</span>]) <span class="op">*</span> <span class="fl">0.9</span>, <span class="bu">max</span>(cal_g.<span class="bu">max</span>().iloc[:<span class="dv">2</span>]) <span class="op">*</span> <span class="fl">1.1</span>]</span>
<span id="cb12-17"><a href="#cb12-17" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].plot(lim, lim, <span class="st">'r--'</span>, linewidth<span class="op">=</span><span class="dv">1</span>, label<span class="op">=</span><span class="st">'Perfect calibration'</span>)</span>
<span id="cb12-18"><a href="#cb12-18" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_xlabel(<span class="st">'Mean Predicted Claim Amount (decile)'</span>)</span>
<span id="cb12-19"><a href="#cb12-19" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_ylabel(<span class="st">'Mean Actual Claim Amount (decile)'</span>)</span>
<span id="cb12-20"><a href="#cb12-20" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_title(<span class="st">'Calibration by Predicted Decile'</span>)</span>
<span id="cb12-21"><a href="#cb12-21" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].legend()</span>
<span id="cb12-22"><a href="#cb12-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-23"><a href="#cb12-23" aria-hidden="true" tabindex="-1"></a><span class="co"># ── Panel 2: the raw scatter, kept but honestly labelled ────────────────────</span></span>
<span id="cb12-24"><a href="#cb12-24" aria-hidden="true" tabindex="-1"></a><span class="co"># Retained because it is the plot everyone expects — and because it shows why</span></span>
<span id="cb12-25"><a href="#cb12-25" aria-hidden="true" tabindex="-1"></a><span class="co"># the diagonal is the wrong reference for a heavy-tailed target. Individual</span></span>
<span id="cb12-26"><a href="#cb12-26" aria-hidden="true" tabindex="-1"></a><span class="co"># claims are draws from a near-exponential conditional distribution; no model</span></span>
<span id="cb12-27"><a href="#cb12-27" aria-hidden="true" tabindex="-1"></a><span class="co"># of the mean can place them on that line.</span></span>
<span id="cb12-28"><a href="#cb12-28" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].scatter(y_test, y_pred, s<span class="op">=</span><span class="dv">6</span>, alpha<span class="op">=</span><span class="fl">0.3</span>, edgecolors<span class="op">=</span><span class="st">'none'</span>, color<span class="op">=</span><span class="st">'#4C72B0'</span>)</span>
<span id="cb12-29"><a href="#cb12-29" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].axhline(y_train.mean(), color<span class="op">=</span><span class="st">'grey'</span>, linestyle<span class="op">=</span><span class="st">':'</span>, linewidth<span class="op">=</span><span class="dv">1</span>,</span>
<span id="cb12-30"><a href="#cb12-30" aria-hidden="true" tabindex="-1"></a>                label<span class="op">=</span><span class="ss">f'Training mean (</span><span class="sc">{</span>y_train<span class="sc">.</span>mean()<span class="sc">:,.0f}</span><span class="ss">)'</span>)</span>
<span id="cb12-31"><a href="#cb12-31" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].plot([y_test.<span class="bu">min</span>(), y_test.<span class="bu">max</span>()], [y_test.<span class="bu">min</span>(), y_test.<span class="bu">max</span>()],</span>
<span id="cb12-32"><a href="#cb12-32" aria-hidden="true" tabindex="-1"></a>             color<span class="op">=</span><span class="st">'r'</span>, linestyle<span class="op">=</span><span class="st">'--'</span>, linewidth<span class="op">=</span><span class="dv">1</span>, label<span class="op">=</span><span class="st">'y = x (not attainable)'</span>)</span>
<span id="cb12-33"><a href="#cb12-33" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_xlabel(<span class="st">'Actual Claim Amount'</span>)</span>
<span id="cb12-34"><a href="#cb12-34" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_ylabel(<span class="st">'Predicted Claim Amount'</span>)</span>
<span id="cb12-35"><a href="#cb12-35" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_title(<span class="st">'Actual vs Predicted (conditional mean)'</span>)</span>
<span id="cb12-36"><a href="#cb12-36" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].legend(fontsize<span class="op">=</span><span class="dv">8</span>)</span>
<span id="cb12-37"><a href="#cb12-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-38"><a href="#cb12-38" aria-hidden="true" tabindex="-1"></a><span class="co"># ── Panel 3: deviance residuals ─────────────────────────────────────────────</span></span>
<span id="cb12-39"><a href="#cb12-39" aria-hidden="true" tabindex="-1"></a><span class="co"># Raw residuals are useless for a Gamma model — their spread grows with the</span></span>
<span id="cb12-40"><a href="#cb12-40" aria-hidden="true" tabindex="-1"></a><span class="co"># mean by construction. Deviance residuals are the ones that should look</span></span>
<span id="cb12-41"><a href="#cb12-41" aria-hidden="true" tabindex="-1"></a><span class="co"># roughly symmetric and homoscedastic if the variance assumption holds.</span></span>
<span id="cb12-42"><a href="#cb12-42" aria-hidden="true" tabindex="-1"></a>dev_resid <span class="op">=</span> result.resid_deviance</span>
<span id="cb12-43"><a href="#cb12-43" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">2</span>].hist(dev_resid, bins<span class="op">=</span><span class="dv">100</span>, edgecolor<span class="op">=</span><span class="st">'white'</span>, color<span class="op">=</span><span class="st">'#4C72B0'</span>)</span>
<span id="cb12-44"><a href="#cb12-44" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">2</span>].axvline(<span class="dv">0</span>, color<span class="op">=</span><span class="st">'r'</span>, linestyle<span class="op">=</span><span class="st">'--'</span>, linewidth<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb12-45"><a href="#cb12-45" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">2</span>].set_title(<span class="st">'Deviance Residuals (train)'</span>)</span>
<span id="cb12-46"><a href="#cb12-46" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">2</span>].set_xlabel(<span class="st">'Deviance residual'</span>)</span>
<span id="cb12-47"><a href="#cb12-47" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">2</span>].set_ylabel(<span class="st">'Frequency'</span>)</span>
<span id="cb12-48"><a href="#cb12-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-49"><a href="#cb12-49" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb12-50"><a href="#cb12-50" aria-hidden="true" tabindex="-1"></a>plt.savefig(<span class="st">'../results/03_glm_predictions.png'</span>, dpi<span class="op">=</span><span class="dv">150</span>, bbox_inches<span class="op">=</span><span class="st">'tight'</span>)</span>
<span id="cb12-51"><a href="#cb12-51" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb12-52"><a href="#cb12-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-53"><a href="#cb12-53" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Calibration by predicted decile:'</span>)</span>
<span id="cb12-54"><a href="#cb12-54" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(cal_g.<span class="bu">round</span>(<span class="dv">0</span>).to_string())</span>
<span id="cb12-55"><a href="#cb12-55" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'</span><span class="ch">\n</span><span class="ss">Actual claim cost, top decile / bottom decile: '</span></span>
<span id="cb12-56"><a href="#cb12-56" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f'</span><span class="sc">{</span>cal_g[<span class="st">"mean_actual"</span>]<span class="sc">.</span>iloc[<span class="op">-</span><span class="dv">1</span>] <span class="op">/</span> cal_g[<span class="st">"mean_actual"</span>]<span class="sc">.</span>iloc[<span class="dv">0</span>]<span class="sc">:.2f}</span><span class="ss">x '</span></span>
<span id="cb12-57"><a href="#cb12-57" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f'(model predicted </span><span class="sc">{</span>cal_g[<span class="st">"mean_pred"</span>]<span class="sc">.</span>iloc[<span class="op">-</span><span class="dv">1</span>] <span class="op">/</span> cal_g[<span class="st">"mean_pred"</span>]<span class="sc">.</span>iloc[<span class="dv">0</span>]<span class="sc">:.2f}</span><span class="ss">x)'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="02_glm_files/figure-html/cell-8-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Calibration by predicted decile:
        mean_pred  mean_actual    n
decile                             
1          1299.0       1278.0  529
2          1395.0       1353.0  529
3          1446.0       1413.0  529
4          1486.0       1707.0  528
5          1525.0       1587.0  529
6          1568.0       1721.0  529
7          1618.0       1522.0  528
8          1687.0       1524.0  529
9          1781.0       1672.0  529
10         1948.0       1802.0  529

Actual claim cost, top decile / bottom decile: 1.41x (model predicted 1.50x)</code></pre>
</div>
</div>
<section id="severity-model-what-it-does-and-does-not-do" class="level3">
<h3 class="anchored" data-anchor-id="severity-model-what-it-does-and-does-not-do">Severity model — what it does and does not do</h3>
<blockquote class="blockquote">
<p>Exact figures to be refreshed from the rerun (the severity split moved from <code>random_state=27</code> to <code>42</code>). The structural findings below are stable across seeds.</p>
</blockquote>
<p><strong>Fit quality.</strong> MAE is roughly €1,100 against a mean claim of €1,569 — an average error of about 70% of the thing being predicted. RMSE (~€2,260) exceeds the mean outright, which is the signature of a heavy right tail rather than of a broken model.</p>
<p><strong>The headline result is how little the features explain.</strong> Deviance explained is ~1.3%, and the correlation between actual and predicted claim size is ~0.05. Scored against an intercept-only model — predicting the training mean for every single claim — the full GLM improves Gamma deviance by well under one percent. Nine rating features and 42 design columns barely beat a constant.</p>
<p><strong>Why the actual-vs-predicted scatter is flat, and why that is not a defect.</strong> A Gamma GLM estimates the conditional mean <span class="math inline">\(E[Y \mid X]\)</span>. It does not, and cannot, estimate the realisation <span class="math inline">\(Y\)</span>. The conditional distribution here is close to exponential (dispersion ≈ 1.06, i.e.&nbsp;shape ≈ 1), so a €16,000 claim is not evidence the model was wrong about that policy — it is an ordinary draw from the upper tail of a distribution whose mean genuinely is around €1,800. Even a <em>perfectly specified</em> model produces exactly this picture. The <span class="math inline">\(y = x\)</span> diagonal is the wrong reference line for a heavy-tailed target, which is why the calibration panel was added: grouped into deciles by predicted value, mean actual tracks mean predicted closely, and the top decile really does cost about 1.4× the bottom decile. The model ranks weakly but is honestly calibrated.</p>
<p>Two corollaries worth stating explicitly, because both are easy to get wrong:</p>
<ul>
<li><strong>Regularisation would not help.</strong> Ridge or lasso penalties fight <em>variance</em> — overfitting. This model has the opposite problem: with ~1.3% deviance explained on the training set there is nothing being overfit, and predictions already span only ~2.9× (≈€870 to €2,500) against actuals spanning 1 to 16,422. Shrinking the coefficients compresses that range further toward the marginal mean, flattening the scatter rather than steepening it.</li>
<li><strong>A more flexible model will not help either.</strong> The ceiling is in the data, not the functional form. Notebooks 03 and 04 test this directly — treat their severity results as the experiment that confirms or refutes it, not as a foregone conclusion.</li>
</ul>
<p><strong>Significant coefficients.</strong> Direction and interpretation still hold:</p>
<ul>
<li><strong>BonusMalus</strong> (positive): worse claims history is associated with higher severity.</li>
<li><strong>VehAge</strong> (negative): older vehicles produce cheaper claims, consistent with lower market value and lower repair cost.</li>
<li><strong>VehPower</strong> (positive): more powerful vehicles are associated with larger claims.</li>
<li><strong>Region</strong> (R93, R94, R41 significant): geographic variation in repair and labour cost.</li>
</ul>
<p>These are the multiplicative rating factors the Gamma GLM exists to produce, and they remain usable for pricing even though per-policy predictive accuracy is near zero — a rating structure needs the <em>relativities</em> right, not the individual realisations.</p>
<p><strong>Key takeaway.</strong> Severity on this dataset is data-limited, not model-limited. The right conclusion is not “the GLM underperforms”, it is “policy features do not predict individual claim cost” — which is a finding about the problem, and one that should carry through to the model comparison in notebook 05.</p>
</section>
</section>
<section id="coefficient-interpretation" class="level2">
<h2 class="anchored" data-anchor-id="coefficient-interpretation">5. Coefficient Interpretation</h2>
<p>Key advantage of GLM over XGBoost/neural net — coefficients are directly interpretable.</p>
<div id="14" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;execution&quot;,&quot;value&quot;:{&quot;iopub.execute_input&quot;:&quot;2026-08-27T15:19:31.349506Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-08-27T15:19:31.349448Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-08-27T15:19:31.352054Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-08-27T15:19:31.351740Z&quot;}}" data-execution_count="8">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># On a log-link GLM, exp(coef) = multiplicative effect on claim amount</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="co"># e.g. exp(coef) = 1.10 means that feature increases expected claim by 10%</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>coef_df <span class="op">=</span> pd.DataFrame({</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">'coef'</span>: result.params,</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">'exp_coef'</span>: np.exp(result.params),</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">'p_value'</span>: result.pvalues,</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(coef_df.sort_values(<span class="st">'exp_coef'</span>, ascending<span class="op">=</span><span class="va">False</span>).head(<span class="dv">10</span>).to_string())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                  coef     exp_coef   p_value
const         7.057657  1161.720065  0.000000
Region_R94    0.290970     1.337725  0.044397
Region_R43    0.277698     1.320088  0.279720
Region_R41    0.237041     1.267493  0.003712
Region_R93    0.221218     1.247595  0.000002
Region_R21    0.216351     1.241538  0.243216
Region_R91    0.211242     1.235212  0.000645
Region_R26    0.131992     1.141099  0.165682
VehBrand_B10  0.097871     1.102821  0.107855
VehBrand_B11  0.094570     1.099186  0.152407</code></pre>
</div>
</div>
<hr>
<section id="appendix-why-gamma-over-ols" class="level3">
<h3 class="anchored" data-anchor-id="appendix-why-gamma-over-ols">Appendix: Why Gamma over OLS?</h3>
<p>Fits a plain OLS regression on the same data and compares it to the Gamma GLM.</p>
<p>The textbook argument against OLS for claim severity is that it assumes constant variance and unbounded support, so it can predict negative claim amounts. Whether that argument actually <em>binds</em> on this dataset is an empirical question, and it is worth answering honestly rather than assuming — the cell below reports what happened, not what was supposed to happen.</p>
<div id="xzdulssq32" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;execution&quot;,&quot;value&quot;:{&quot;iopub.execute_input&quot;:&quot;2026-08-27T15:19:31.352992Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-08-27T15:19:31.352938Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-08-27T15:19:31.410955Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-08-27T15:19:31.410640Z&quot;}}" data-execution_count="9">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.linear_model <span class="im">import</span> LinearRegression</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>ols <span class="op">=</span> LinearRegression().fit(X_train, y_train)</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>y_pred_ols <span class="op">=</span> ols.predict(X_test)</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>mae_ols  <span class="op">=</span> mean_absolute_error(y_test, y_pred_ols)</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>rmse_ols <span class="op">=</span> mean_squared_error(y_test, y_pred_ols) <span class="op">**</span> <span class="fl">0.5</span></span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>n_negative <span class="op">=</span> (y_pred_ols <span class="op">&lt;</span> <span class="dv">0</span>).<span class="bu">sum</span>()</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'</span><span class="sc">{</span><span class="st">""</span><span class="sc">:20}</span><span class="ss"> </span><span class="sc">{</span><span class="st">"GLM"</span><span class="sc">:&gt;12}</span><span class="ss"> </span><span class="sc">{</span><span class="st">"OLS"</span><span class="sc">:&gt;12}</span><span class="ss">'</span>)</span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'</span><span class="sc">{</span><span class="st">"MAE"</span><span class="sc">:20}</span><span class="ss"> </span><span class="sc">{</span>mae<span class="sc">:&gt;12,.2f}</span><span class="ss"> </span><span class="sc">{</span>mae_ols<span class="sc">:&gt;12,.2f}</span><span class="ss">'</span>)</span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'</span><span class="sc">{</span><span class="st">"RMSE"</span><span class="sc">:20}</span><span class="ss"> </span><span class="sc">{</span>rmse<span class="sc">:&gt;12,.2f}</span><span class="ss"> </span><span class="sc">{</span>rmse_ols<span class="sc">:&gt;12,.2f}</span><span class="ss">'</span>)</span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'</span><span class="sc">{</span><span class="st">"Min prediction"</span><span class="sc">:20}</span><span class="ss"> </span><span class="sc">{</span>y_pred<span class="sc">.</span><span class="bu">min</span>()<span class="sc">:&gt;12,.0f}</span><span class="ss"> </span><span class="sc">{</span>y_pred_ols<span class="sc">.</span><span class="bu">min</span>()<span class="sc">:&gt;12,.0f}</span><span class="ss">'</span>)</span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'</span><span class="sc">{</span><span class="st">"Negative preds"</span><span class="sc">:20}</span><span class="ss"> </span><span class="sc">{</span><span class="dv">0</span><span class="sc">:&gt;12,}</span><span class="ss"> </span><span class="sc">{</span>n_negative<span class="sc">:&gt;12,}</span><span class="ss">'</span>)</span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-17"><a href="#cb16-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'</span><span class="ch">\n</span><span class="ss">OLS negative predictions: </span><span class="sc">{</span>n_negative<span class="sc">}</span><span class="ss"> (</span><span class="sc">{</span>n_negative<span class="op">/</span><span class="bu">len</span>(y_pred_ols)<span class="sc">:.1%}</span><span class="ss">)'</span>)</span>
<span id="cb16-18"><a href="#cb16-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-19"><a href="#cb16-19" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> n_negative <span class="op">==</span> <span class="dv">0</span>:</span>
<span id="cb16-20"><a href="#cb16-20" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(</span>
<span id="cb16-21"><a href="#cb16-21" aria-hidden="true" tabindex="-1"></a>        <span class="st">'</span><span class="ch">\n</span><span class="st">The positivity argument does not bind here. Because the features explain almost</span><span class="ch">\n</span><span class="st">'</span></span>
<span id="cb16-22"><a href="#cb16-22" aria-hidden="true" tabindex="-1"></a>        <span class="st">'none of the variation in claim size, both models collapse to predicting something</span><span class="ch">\n</span><span class="st">'</span></span>
<span id="cb16-23"><a href="#cb16-23" aria-hidden="true" tabindex="-1"></a>        <span class="ss">f'close to the marginal mean (</span><span class="sc">{</span>y_train<span class="sc">.</span>mean()<span class="sc">:,.0f}</span><span class="ss"> EUR) for every policy — nowhere</span><span class="ch">\n</span><span class="ss">'</span></span>
<span id="cb16-24"><a href="#cb16-24" aria-hidden="true" tabindex="-1"></a>        <span class="st">'near zero, so OLS never crosses into negative territory. MAE and RMSE are</span><span class="ch">\n</span><span class="st">'</span></span>
<span id="cb16-25"><a href="#cb16-25" aria-hidden="true" tabindex="-1"></a>        <span class="st">'correspondingly near-identical: neither model is extracting signal the other misses.'</span></span>
<span id="cb16-26"><a href="#cb16-26" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb16-27"><a href="#cb16-27" aria-hidden="true" tabindex="-1"></a><span class="cf">else</span>:</span>
<span id="cb16-28"><a href="#cb16-28" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f'</span><span class="ch">\n</span><span class="ss">OLS predicted a negative claim amount for </span><span class="sc">{</span>n_negative<span class="sc">}</span><span class="ss"> policies, which is '</span></span>
<span id="cb16-29"><a href="#cb16-29" aria-hidden="true" tabindex="-1"></a>          <span class="st">'structurally impossible and disqualifies it on its own.'</span>)</span>
<span id="cb16-30"><a href="#cb16-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-31"><a href="#cb16-31" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(</span>
<span id="cb16-32"><a href="#cb16-32" aria-hidden="true" tabindex="-1"></a>    <span class="st">'</span><span class="ch">\n</span><span class="st">The Gamma GLM is still the right specification, but on distributional grounds</span><span class="ch">\n</span><span class="st">'</span></span>
<span id="cb16-33"><a href="#cb16-33" aria-hidden="true" tabindex="-1"></a>    <span class="st">'rather than on these error metrics:</span><span class="ch">\n</span><span class="st">'</span></span>
<span id="cb16-34"><a href="#cb16-34" aria-hidden="true" tabindex="-1"></a>    <span class="st">'  1. Variance structure. Gamma assumes Var(Y) proportional to mu^2 — proportional</span><span class="ch">\n</span><span class="st">'</span></span>
<span id="cb16-35"><a href="#cb16-35" aria-hidden="true" tabindex="-1"></a>    <span class="st">'     error. OLS assumes constant variance, which is plainly false for claim sizes</span><span class="ch">\n</span><span class="st">'</span></span>
<span id="cb16-36"><a href="#cb16-36" aria-hidden="true" tabindex="-1"></a>    <span class="st">'     spanning 1 to 16,000 EUR, so its standard errors and p-values are not</span><span class="ch">\n</span><span class="st">'</span></span>
<span id="cb16-37"><a href="#cb16-37" aria-hidden="true" tabindex="-1"></a>    <span class="st">'     trustworthy even when its point predictions are fine.</span><span class="ch">\n</span><span class="st">'</span></span>
<span id="cb16-38"><a href="#cb16-38" aria-hidden="true" tabindex="-1"></a>    <span class="st">'  2. Rating structure. The log link makes coefficients multiplicative rating</span><span class="ch">\n</span><span class="st">'</span></span>
<span id="cb16-39"><a href="#cb16-39" aria-hidden="true" tabindex="-1"></a>    <span class="st">'     factors, the form actuaries and regulators already read. OLS gives additive</span><span class="ch">\n</span><span class="st">'</span></span>
<span id="cb16-40"><a href="#cb16-40" aria-hidden="true" tabindex="-1"></a>    <span class="st">'     ones, which is not how premium is built.</span><span class="ch">\n</span><span class="st">'</span></span>
<span id="cb16-41"><a href="#cb16-41" aria-hidden="true" tabindex="-1"></a>    <span class="st">'  3. Out-of-sample safety. Positivity is guaranteed by construction rather than by</span><span class="ch">\n</span><span class="st">'</span></span>
<span id="cb16-42"><a href="#cb16-42" aria-hidden="true" tabindex="-1"></a>    <span class="st">'     luck. It did not bind on this test set; on a portfolio with cheaper claims or</span><span class="ch">\n</span><span class="st">'</span></span>
<span id="cb16-43"><a href="#cb16-43" aria-hidden="true" tabindex="-1"></a>    <span class="st">'     more extreme covariates it would.</span><span class="ch">\n</span><span class="st">'</span></span>
<span id="cb16-44"><a href="#cb16-44" aria-hidden="true" tabindex="-1"></a>    <span class="st">'</span><span class="ch">\n</span><span class="st">What this appendix actually establishes is weaker than "OLS is wrong": on this data</span><span class="ch">\n</span><span class="st">'</span></span>
<span id="cb16-45"><a href="#cb16-45" aria-hidden="true" tabindex="-1"></a>    <span class="st">'the choice of link and error family barely moves predictive accuracy, because there</span><span class="ch">\n</span><span class="st">'</span></span>
<span id="cb16-46"><a href="#cb16-46" aria-hidden="true" tabindex="-1"></a>    <span class="st">'is so little to predict. The case for Gamma rests on inference and interpretability.'</span></span>
<span id="cb16-47"><a href="#cb16-47" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                              GLM          OLS
MAE                      1,102.26     1,102.44
RMSE                     2,261.57     2,261.32
Min prediction                873          713
Negative preds                  0            0

OLS negative predictions: 0 (0.0%)

The positivity argument does not bind here. Because the features explain almost
none of the variation in claim size, both models collapse to predicting something
close to the marginal mean (1,572 EUR) for every policy — nowhere
near zero, so OLS never crosses into negative territory. MAE and RMSE are
correspondingly near-identical: neither model is extracting signal the other misses.

The Gamma GLM is still the right specification, but on distributional grounds
rather than on these error metrics:
  1. Variance structure. Gamma assumes Var(Y) proportional to mu^2 — proportional
     error. OLS assumes constant variance, which is plainly false for claim sizes
     spanning 1 to 16,000 EUR, so its standard errors and p-values are not
     trustworthy even when its point predictions are fine.
  2. Rating structure. The log link makes coefficients multiplicative rating
     factors, the form actuaries and regulators already read. OLS gives additive
     ones, which is not how premium is built.
  3. Out-of-sample safety. Positivity is guaranteed by construction rather than by
     luck. It did not bind on this test set; on a portfolio with cheaper claims or
     more extreme covariates it would.

What this appendix actually establishes is weaker than "OLS is wrong": on this data
the choice of link and error family barely moves predictive accuracy, because there
is so little to predict. The case for Gamma rests on inference and interpretability.</code></pre>
</div>
</div>
<hr>
</section>
<section id="appendix-b-model-selection-for-severity" class="level3">
<h3 class="anchored" data-anchor-id="appendix-b-model-selection-for-severity">Appendix B: Model Selection for Severity</h3>
<p>The severity model above is a Gamma GLM, chosen on theoretical grounds: claim amounts are positive, right-skewed, and plausibly have proportional rather than additive error. That is a justification by <em>convention</em> — the Gamma GLM has been the industry workhorse since McCullagh and Nelder fitted GLMs to motor data in the early 1980s. Convention is a reason to start there; it is not evidence that it is the right choice for <em>this</em> data.</p>
<p>The flat actual-vs-predicted scatter above makes the question concrete. Three explanations are possible, and they call for completely different fixes:</p>
<ol type="1">
<li><strong>Wrong error distribution.</strong> The Gamma is light-tailed — its density decays exponentially — so genuinely extreme claims are treated as near-impossible events. A heavier-tailed family might fit better.</li>
<li><strong>Wrong mean function.</strong> The GLM forces <span class="math inline">\(\log E[Y|X]\)</span> to be <em>linear</em> in the features. If the true relationship bends or interacts, a linear model cannot represent it.</li>
<li><strong>Nothing to fit.</strong> The features may simply not carry information about individual claim size, in which case no model of any kind will do better.</li>
</ol>
<p>These are distinguishable by experiment, so this appendix runs it. Each subsection tests one of the three.</p>
<section id="b.1-the-candidates" class="level4">
<h4 class="anchored" data-anchor-id="b.1-the-candidates">B.1 The candidates</h4>
<p>Models 1–6 all share the <strong>same linear predictor</strong> — the same 42 design columns, entering linearly. What differs is the assumed relationship between the mean and the variance, and (for 5 and 6) the link. Holding the mean function fixed isolates the effect of the distributional assumption, which is exactly question 1.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>#</th>
<th>Model</th>
<th>Variance assumption</th>
<th>What it buys</th>
<th>What it costs</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0</td>
<td>Intercept only</td>
<td>—</td>
<td>The benchmark every model must beat</td>
<td>Ignores the features entirely</td>
</tr>
<tr class="even">
<td>1</td>
<td>Gamma GLM</td>
<td><span class="math inline">\(\text{Var}(Y) \propto \mu^2\)</span></td>
<td>Multiplicative rating factors; industry standard</td>
<td>Light-tailed; not robust to outliers</td>
</tr>
<tr class="odd">
<td>2</td>
<td>Inverse Gaussian GLM</td>
<td><span class="math inline">\(\text{Var}(Y) \propto \mu^3\)</span></td>
<td>Heavier tail; more tolerant of extremes</td>
<td>Less standard; dispersion harder to read</td>
</tr>
<tr class="even">
<td>3</td>
<td>Tweedie GLM (<span class="math inline">\(p{=}1.5\)</span>)</td>
<td><span class="math inline">\(\text{Var}(Y) \propto \mu^{1.5}\)</span></td>
<td>Interpolates between Poisson and Gamma</td>
<td>Extra parameter to choose</td>
</tr>
<tr class="odd">
<td>4</td>
<td>Gaussian GLM, log link</td>
<td><span class="math inline">\(\text{Var}(Y) = \sigma^2\)</span></td>
<td>Isolates the <em>variance</em> assumption from the <em>link</em></td>
<td>Constant variance is clearly false here</td>
</tr>
<tr class="even">
<td>5</td>
<td>Lognormal + smearing</td>
<td>Normal on <span class="math inline">\(\log Y\)</span></td>
<td>Genuinely heavy-tailed on the original scale</td>
<td>Predicts the <strong>median</strong>; needs retransformation</td>
</tr>
<tr class="odd">
<td>6</td>
<td>OLS, identity link</td>
<td><span class="math inline">\(\text{Var}(Y) = \sigma^2\)</span></td>
<td>The naive baseline</td>
<td>Additive effects; unbounded support</td>
</tr>
<tr class="even">
<td>7</td>
<td>Gradient boosting</td>
<td>Gamma loss</td>
<td><strong>Drops linearity</strong> — arbitrary shapes and interactions</td>
<td>No coefficients; cannot extrapolate</td>
</tr>
</tbody>
</table>
<p><strong>Why the variance assumption matters at all.</strong> In a GLM the variance function sets the <em>weighting</em>. Under Gamma’s <span class="math inline">\(\text{Var} \propto \mu^2\)</span> the coefficient of variation is constant, so a €10,000 claim is expected to miss by ten times as much, in euros, as a €1,000 claim — errors are judged proportionally. Under Gaussian’s constant variance every claim is weighted equally in absolute euros, so the large claims dominate the fit. These are genuinely different estimators, and if the distribution is what constrains us, they should give visibly different answers.</p>
<p><strong>A note on model 5.</strong> Fitting OLS to <span class="math inline">\(\log Y\)</span> and exponentiating does <em>not</em> estimate <span class="math inline">\(E[Y|X]\)</span> — it estimates the conditional <strong>median</strong>, because <span class="math inline">\(E[\exp(\varepsilon)] \neq
\exp(E[\varepsilon])\)</span> by Jensen’s inequality. Duan’s smearing estimator corrects this by multiplying through by <span class="math inline">\(\frac{1}{n}\sum_i \exp(\hat{\varepsilon}_i)\)</span>. Without that correction the comparison would be unfair — it would be scoring a median against a mean.</p>
<p><strong>Model 7 answers question 2.</strong> Gradient boosting on trees makes no linearity assumption at all: it learns whatever shape and interactions the data support, while still optimising Gamma deviance. If linearity were the binding constraint, this is where it would show.</p>
<div id="appx-b-compare" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;execution&quot;,&quot;value&quot;:{&quot;iopub.execute_input&quot;:&quot;2026-08-27T15:19:31.412076Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-08-27T15:19:31.412006Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-08-27T15:19:32.174978Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-08-27T15:19:32.174311Z&quot;}}" data-execution_count="10">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ── Candidate severity models, all scored on the same test rows ──────────────</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.ensemble <span class="im">import</span> HistGradientBoostingRegressor</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.linear_model <span class="im">import</span> LinearRegression</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> gini_coef(actual, predicted):</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Normalised Gini — how well the model RANKS claims by size. 0 = no better</span></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a><span class="co">    than random ordering, 1 = perfect. This is the metric that matters for a</span></span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a><span class="co">    rating structure, which needs relativities right rather than realisations."""</span></span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>    d <span class="op">=</span> pd.DataFrame({<span class="st">'a'</span>: np.asarray(actual), <span class="st">'p'</span>: np.asarray(predicted)}).sort_values(<span class="st">'p'</span>, ascending<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>    g <span class="op">=</span> <span class="dv">1</span> <span class="op">-</span> <span class="dv">2</span> <span class="op">*</span> (d[<span class="st">'a'</span>].cumsum() <span class="op">/</span> d[<span class="st">'a'</span>].<span class="bu">sum</span>()).mean()</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>    perfect <span class="op">=</span> np.sort(np.asarray(actual))[::<span class="op">-</span><span class="dv">1</span>]</span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> g <span class="op">/</span> (<span class="dv">1</span> <span class="op">-</span> <span class="dv">2</span> <span class="op">*</span> (np.cumsum(perfect) <span class="op">/</span> perfect.<span class="bu">sum</span>()).mean())</span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> score(name, pred):</span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a>    pred <span class="op">=</span> np.clip(np.asarray(pred, dtype<span class="op">=</span><span class="bu">float</span>), <span class="fl">1e-6</span>, <span class="va">None</span>)</span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> {<span class="st">'Model'</span>: name,</span>
<span id="cb18-17"><a href="#cb18-17" aria-hidden="true" tabindex="-1"></a>            <span class="st">'Gamma Deviance'</span>: gamma_deviance(y_test.values, pred),</span>
<span id="cb18-18"><a href="#cb18-18" aria-hidden="true" tabindex="-1"></a>            <span class="st">'MAE'</span>:  mean_absolute_error(y_test, pred),</span>
<span id="cb18-19"><a href="#cb18-19" aria-hidden="true" tabindex="-1"></a>            <span class="st">'RMSE'</span>: mean_squared_error(y_test, pred) <span class="op">**</span> <span class="fl">0.5</span>,</span>
<span id="cb18-20"><a href="#cb18-20" aria-hidden="true" tabindex="-1"></a>            <span class="st">'Gini'</span>: gini_coef(y_test.values, pred),</span>
<span id="cb18-21"><a href="#cb18-21" aria-hidden="true" tabindex="-1"></a>            <span class="st">'Pred spread'</span>: pred.<span class="bu">max</span>() <span class="op">/</span> pred.<span class="bu">min</span>()}</span>
<span id="cb18-22"><a href="#cb18-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-23"><a href="#cb18-23" aria-hidden="true" tabindex="-1"></a>rows <span class="op">=</span> [score(<span class="st">'0. Intercept only'</span>, np.full(<span class="bu">len</span>(y_test), y_train.mean()))]</span>
<span id="cb18-24"><a href="#cb18-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-25"><a href="#cb18-25" aria-hidden="true" tabindex="-1"></a><span class="co"># --- GLMs: same log link and same mean function, different variance assumptions</span></span>
<span id="cb18-26"><a href="#cb18-26" aria-hidden="true" tabindex="-1"></a>glm_families <span class="op">=</span> [</span>
<span id="cb18-27"><a href="#cb18-27" aria-hidden="true" tabindex="-1"></a>    (<span class="st">'1. Gamma GLM'</span>,            sm.families.Gamma(sm.families.links.Log())),</span>
<span id="cb18-28"><a href="#cb18-28" aria-hidden="true" tabindex="-1"></a>    (<span class="st">'2. Inverse Gaussian GLM'</span>, sm.families.InverseGaussian(sm.families.links.Log())),</span>
<span id="cb18-29"><a href="#cb18-29" aria-hidden="true" tabindex="-1"></a>    (<span class="st">'3. Tweedie GLM (p=1.5)'</span>,  sm.families.Tweedie(sm.families.links.Log(), var_power<span class="op">=</span><span class="fl">1.5</span>)),</span>
<span id="cb18-30"><a href="#cb18-30" aria-hidden="true" tabindex="-1"></a>    (<span class="st">'4. Gaussian GLM (log)'</span>,   sm.families.Gaussian(sm.families.links.Log())),</span>
<span id="cb18-31"><a href="#cb18-31" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb18-32"><a href="#cb18-32" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> nm, fam <span class="kw">in</span> glm_families:</span>
<span id="cb18-33"><a href="#cb18-33" aria-hidden="true" tabindex="-1"></a>    rows.append(score(nm, sm.GLM(y_train, X_train_sm, family<span class="op">=</span>fam).fit().predict(X_test_sm)))</span>
<span id="cb18-34"><a href="#cb18-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-35"><a href="#cb18-35" aria-hidden="true" tabindex="-1"></a><span class="co"># --- Lognormal: fit OLS on log(y), then retransform. exp(Xb) estimates the</span></span>
<span id="cb18-36"><a href="#cb18-36" aria-hidden="true" tabindex="-1"></a><span class="co">#     MEDIAN, not the mean, so Duan's smearing factor corrects the bias.</span></span>
<span id="cb18-37"><a href="#cb18-37" aria-hidden="true" tabindex="-1"></a>ln <span class="op">=</span> sm.OLS(np.log(y_train), X_train_sm).fit()</span>
<span id="cb18-38"><a href="#cb18-38" aria-hidden="true" tabindex="-1"></a>smearing <span class="op">=</span> np.mean(np.exp(ln.resid))</span>
<span id="cb18-39"><a href="#cb18-39" aria-hidden="true" tabindex="-1"></a>rows.append(score(<span class="st">'5. Lognormal (+smearing)'</span>, np.exp(ln.predict(X_test_sm)) <span class="op">*</span> smearing))</span>
<span id="cb18-40"><a href="#cb18-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-41"><a href="#cb18-41" aria-hidden="true" tabindex="-1"></a><span class="co"># --- OLS on the raw scale: the naive baseline</span></span>
<span id="cb18-42"><a href="#cb18-42" aria-hidden="true" tabindex="-1"></a>rows.append(score(<span class="st">'6. OLS (identity link)'</span>, LinearRegression().fit(X_train, y_train).predict(X_test)))</span>
<span id="cb18-43"><a href="#cb18-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-44"><a href="#cb18-44" aria-hidden="true" tabindex="-1"></a><span class="co"># --- Gradient boosting: drops the linearity assumption entirely</span></span>
<span id="cb18-45"><a href="#cb18-45" aria-hidden="true" tabindex="-1"></a>gbm <span class="op">=</span> HistGradientBoostingRegressor(loss<span class="op">=</span><span class="st">'gamma'</span>, max_iter<span class="op">=</span><span class="dv">400</span>, learning_rate<span class="op">=</span><span class="fl">0.03</span>,</span>
<span id="cb18-46"><a href="#cb18-46" aria-hidden="true" tabindex="-1"></a>                                    max_leaf_nodes<span class="op">=</span><span class="dv">15</span>, min_samples_leaf<span class="op">=</span><span class="dv">100</span>,</span>
<span id="cb18-47"><a href="#cb18-47" aria-hidden="true" tabindex="-1"></a>                                    l2_regularization<span class="op">=</span><span class="fl">1.0</span>, random_state<span class="op">=</span><span class="dv">42</span>).fit(X_train, y_train)</span>
<span id="cb18-48"><a href="#cb18-48" aria-hidden="true" tabindex="-1"></a>rows.append(score(<span class="st">'7. Gradient boosting (gamma loss)'</span>, gbm.predict(X_test)))</span>
<span id="cb18-49"><a href="#cb18-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-50"><a href="#cb18-50" aria-hidden="true" tabindex="-1"></a>candidates <span class="op">=</span> pd.DataFrame(rows).set_index(<span class="st">'Model'</span>)</span>
<span id="cb18-51"><a href="#cb18-51" aria-hidden="true" tabindex="-1"></a>null_dev <span class="op">=</span> candidates.loc[<span class="st">'0. Intercept only'</span>, <span class="st">'Gamma Deviance'</span>]</span>
<span id="cb18-52"><a href="#cb18-52" aria-hidden="true" tabindex="-1"></a>candidates[<span class="st">'vs null'</span>] <span class="op">=</span> (null_dev <span class="op">-</span> candidates[<span class="st">'Gamma Deviance'</span>]) <span class="op">/</span> null_dev</span>
<span id="cb18-53"><a href="#cb18-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-54"><a href="#cb18-54" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'=== Severity candidates, test set (n = </span><span class="sc">{</span><span class="bu">len</span>(y_test)<span class="sc">:,}</span><span class="ss">) ===</span><span class="ch">\n</span><span class="ss">'</span>)</span>
<span id="cb18-55"><a href="#cb18-55" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(candidates.assign(<span class="op">**</span>{<span class="st">'vs null'</span>: candidates[<span class="st">'vs null'</span>].<span class="bu">map</span>(<span class="st">'</span><span class="sc">{:+.3%}</span><span class="st">'</span>.<span class="bu">format</span>)})</span>
<span id="cb18-56"><a href="#cb18-56" aria-hidden="true" tabindex="-1"></a>      .<span class="bu">round</span>({<span class="st">'Gamma Deviance'</span>: <span class="dv">4</span>, <span class="st">'MAE'</span>: <span class="dv">2</span>, <span class="st">'RMSE'</span>: <span class="dv">2</span>, <span class="st">'Gini'</span>: <span class="dv">4</span>, <span class="st">'Pred spread'</span>: <span class="dv">2</span>}).to_string())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>=== Severity candidates, test set (n = 5,288) ===

                                   Gamma Deviance      MAE     RMSE    Gini  Pred spread  vs null
Model                                                                                            
0. Intercept only                          1.0642  1104.71  2263.58  0.0056         1.00  +0.000%
1. Gamma GLM                               1.0595  1102.26  2261.57  0.0959         2.87  +0.440%
2. Inverse Gaussian GLM                    1.0596  1103.11  2261.74  0.0967         2.82  +0.435%
3. Tweedie GLM (p=1.5)                     1.0595  1102.06  2261.53  0.0955         2.90  +0.438%
4. Gaussian GLM (log)                      1.0598  1101.98  2261.54  0.0940         3.01  +0.414%
5. Lognormal (+smearing)                   1.0639  1115.44  2265.83  0.0916         3.36  +0.024%
6. OLS (identity link)                     1.0595  1102.44  2261.32  0.0951         3.38  +0.443%
7. Gradient boosting (gamma loss)          1.0522  1081.66  2257.01  0.1311         2.02  +1.130%</code></pre>
</div>
</div>
<p><strong>Reading the head-to-head.</strong></p>
<p>Two results stand out, and they answer questions 1 and 2 respectively.</p>
<p><strong>The error distribution makes almost no difference.</strong> Models 1, 2, 3, 4 and 6 land within 0.03 percentage points of each other — Gamma +0.440%, Inverse Gaussian +0.435%, Tweedie +0.438%, Gaussian-log +0.414%, OLS +0.443%. Gamma, a cubic variance function, a constant variance function and an additive link all reach the same place. Whatever is limiting this model, it is <strong>not</strong> the distributional assumption. That is question 1 answered: no.</p>
<p>The lognormal is the one clear loser (+0.024%, essentially the null model). Its assumption — that errors are homoscedastic on the log scale — is worse-matched to this data than the alternatives, and the smearing retransformation cannot repair it. This is worth noting because “just model <span class="math inline">\(\log(\text{ClaimAmount})\)</span>” is a common reflex for skewed targets, and here it actively hurts.</p>
<p><strong>Gradient boosting appears to win.</strong> It posts +1.13% against the GLM’s +0.440% and lifts Gini from 0.096 to 0.131 — a 37% relative improvement in ranking. Taken at face value that would answer question 2 with “yes, linearity was the constraint.”</p>
<p>It should not be taken at face value. The severity test set is ~5,300 claims and the target is extraordinarily noisy, which is precisely the regime where a single train/test split cannot distinguish a real improvement from a lucky one. Section B.2 tests it properly.</p>
<p><strong>Also worth noting:</strong> the intercept-only model has Gini 0.006, confirming the metric behaves — a model with no features cannot rank. And every model’s prediction spread is just 2.0–3.4× against actuals spanning 1 to 16,451, which is the flat scatter restated numerically.</p>
</section>
<section id="b.2-is-the-boosting-advantage-real" class="level4">
<h4 class="anchored" data-anchor-id="b.2-is-the-boosting-advantage-real">B.2 Is the boosting advantage real?</h4>
<p>A single split gives one number with no error bar. With ~5,300 test claims and a target this noisy, the split-to-split variation can easily exceed the difference between two models — and published benchmarks on this dataset report exactly that problem, with fold-to-fold variance large enough to reorder the leaderboard.</p>
<p>The fix is <strong>repeated k-fold cross-validation with a paired comparison</strong>: fit both models on the same folds, take the difference <em>within</em> each fold, and test whether the mean difference is distinguishable from zero. Pairing matters — it removes fold difficulty as a source of variance, so the test is far more sensitive than comparing two independent averages.</p>
<div id="appx-b-cv" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;execution&quot;,&quot;value&quot;:{&quot;iopub.execute_input&quot;:&quot;2026-08-27T15:19:32.176286Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-08-27T15:19:32.176221Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-08-27T15:19:36.699518Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-08-27T15:19:36.698899Z&quot;}}" data-execution_count="11">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ── Is the gradient boosting advantage real, or an artefact of one split? ────</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="co"># The severity test set is only ~5,300 claims and the target is extremely noisy,</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="co"># so a single split cannot separate a genuine improvement from a lucky one.</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Repeated k-fold CV gives a per-fold paired comparison instead of one number.</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.model_selection <span class="im">import</span> KFold</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy <span class="im">import</span> stats</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>X_res, y_res <span class="op">=</span> X.reset_index(drop<span class="op">=</span><span class="va">True</span>), y.reset_index(drop<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>fold_glm, fold_gbm, fold_null <span class="op">=</span> [], [], []</span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> seed <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">3</span>):                                   <span class="co"># 3 seeds x 5 folds = 15 comparisons</span></span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> tr, te <span class="kw">in</span> KFold(<span class="dv">5</span>, shuffle<span class="op">=</span><span class="va">True</span>, random_state<span class="op">=</span>seed).split(X_res):</span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a>        Xtr, Xte <span class="op">=</span> X_res.iloc[tr], X_res.iloc[te]</span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a>        ytr, yte <span class="op">=</span> y_res.iloc[tr], y_res.iloc[te]</span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-16"><a href="#cb20-16" aria-hidden="true" tabindex="-1"></a>        fold_null.append(gamma_deviance(yte.values, np.full(<span class="bu">len</span>(yte), ytr.mean())))</span>
<span id="cb20-17"><a href="#cb20-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-18"><a href="#cb20-18" aria-hidden="true" tabindex="-1"></a>        p_glm <span class="op">=</span> sm.GLM(ytr, sm.add_constant(Xtr),</span>
<span id="cb20-19"><a href="#cb20-19" aria-hidden="true" tabindex="-1"></a>                       family<span class="op">=</span>sm.families.Gamma(sm.families.links.Log())).fit().predict(sm.add_constant(Xte))</span>
<span id="cb20-20"><a href="#cb20-20" aria-hidden="true" tabindex="-1"></a>        fold_glm.append((gamma_deviance(yte.values, p_glm.values), gini_coef(yte.values, p_glm.values)))</span>
<span id="cb20-21"><a href="#cb20-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-22"><a href="#cb20-22" aria-hidden="true" tabindex="-1"></a>        p_gbm <span class="op">=</span> HistGradientBoostingRegressor(loss<span class="op">=</span><span class="st">'gamma'</span>, max_iter<span class="op">=</span><span class="dv">400</span>, learning_rate<span class="op">=</span><span class="fl">0.03</span>,</span>
<span id="cb20-23"><a href="#cb20-23" aria-hidden="true" tabindex="-1"></a>                                              max_leaf_nodes<span class="op">=</span><span class="dv">15</span>, min_samples_leaf<span class="op">=</span><span class="dv">100</span>,</span>
<span id="cb20-24"><a href="#cb20-24" aria-hidden="true" tabindex="-1"></a>                                              l2_regularization<span class="op">=</span><span class="fl">1.0</span>, random_state<span class="op">=</span><span class="dv">42</span>).fit(Xtr, ytr).predict(Xte)</span>
<span id="cb20-25"><a href="#cb20-25" aria-hidden="true" tabindex="-1"></a>        fold_gbm.append((gamma_deviance(yte.values, p_gbm), gini_coef(yte.values, p_gbm)))</span>
<span id="cb20-26"><a href="#cb20-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-27"><a href="#cb20-27" aria-hidden="true" tabindex="-1"></a>null_d <span class="op">=</span> np.array(fold_null)</span>
<span id="cb20-28"><a href="#cb20-28" aria-hidden="true" tabindex="-1"></a>glm_d, glm_g <span class="op">=</span> np.array([f[<span class="dv">0</span>] <span class="cf">for</span> f <span class="kw">in</span> fold_glm]), np.array([f[<span class="dv">1</span>] <span class="cf">for</span> f <span class="kw">in</span> fold_glm])</span>
<span id="cb20-29"><a href="#cb20-29" aria-hidden="true" tabindex="-1"></a>gbm_d, gbm_g <span class="op">=</span> np.array([f[<span class="dv">0</span>] <span class="cf">for</span> f <span class="kw">in</span> fold_gbm]), np.array([f[<span class="dv">1</span>] <span class="cf">for</span> f <span class="kw">in</span> fold_gbm])</span>
<span id="cb20-30"><a href="#cb20-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-31"><a href="#cb20-31" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'</span><span class="sc">{</span><span class="bu">len</span>(null_d)<span class="sc">}</span><span class="ss"> folds (5-fold CV x 3 seeds), mean +/- sd</span><span class="ch">\n</span><span class="ss">'</span>)</span>
<span id="cb20-32"><a href="#cb20-32" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'</span><span class="sc">{</span><span class="st">""</span><span class="sc">:22}</span><span class="ss"> </span><span class="sc">{</span><span class="st">"Gamma Deviance"</span><span class="sc">:&gt;22}</span><span class="ss"> </span><span class="sc">{</span><span class="st">"Gini"</span><span class="sc">:&gt;18}</span><span class="ss"> </span><span class="sc">{</span><span class="st">"vs null"</span><span class="sc">:&gt;10}</span><span class="ss">'</span>)</span>
<span id="cb20-33"><a href="#cb20-33" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> nm, d, gg <span class="kw">in</span> [(<span class="st">'Intercept only'</span>, null_d, np.zeros_like(null_d)), (<span class="st">'Gamma GLM'</span>, glm_d, glm_g),</span>
<span id="cb20-34"><a href="#cb20-34" aria-hidden="true" tabindex="-1"></a>                  (<span class="st">'Gradient boosting'</span>, gbm_d, gbm_g)]:</span>
<span id="cb20-35"><a href="#cb20-35" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f'</span><span class="sc">{</span>nm<span class="sc">:22}</span><span class="ss"> </span><span class="sc">{</span>d<span class="sc">.</span>mean()<span class="sc">:&gt;10.4f}</span><span class="ss"> +/- </span><span class="sc">{</span>d<span class="sc">.</span>std()<span class="sc">:&lt;8.4f}</span><span class="ss"> </span><span class="sc">{</span>gg<span class="sc">.</span>mean()<span class="sc">:&gt;8.4f}</span><span class="ss"> +/- </span><span class="sc">{</span>gg<span class="sc">.</span>std()<span class="sc">:&lt;6.4f}</span><span class="ss"> '</span></span>
<span id="cb20-36"><a href="#cb20-36" aria-hidden="true" tabindex="-1"></a>          <span class="ss">f'</span><span class="sc">{</span>(null_d <span class="op">-</span> d)<span class="sc">.</span>mean() <span class="op">/</span> null_d<span class="sc">.</span>mean()<span class="sc">:&gt;+9.3%}</span><span class="ss">'</span>)</span>
<span id="cb20-37"><a href="#cb20-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-38"><a href="#cb20-38" aria-hidden="true" tabindex="-1"></a>diff <span class="op">=</span> gbm_g <span class="op">-</span> glm_g</span>
<span id="cb20-39"><a href="#cb20-39" aria-hidden="true" tabindex="-1"></a>ttest <span class="op">=</span> stats.ttest_rel(gbm_g, glm_g)</span>
<span id="cb20-40"><a href="#cb20-40" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'</span><span class="ch">\n</span><span class="ss">Gini advantage of boosting over the GLM, measured per fold:'</span>)</span>
<span id="cb20-41"><a href="#cb20-41" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'  mean difference   </span><span class="sc">{</span>diff<span class="sc">.</span>mean()<span class="sc">:+.4f}</span><span class="ss"> +/- </span><span class="sc">{</span>diff<span class="sc">.</span>std()<span class="sc">:.4f}</span><span class="ss">'</span>)</span>
<span id="cb20-42"><a href="#cb20-42" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'  folds boosting won  </span><span class="sc">{</span>(diff <span class="op">&gt;</span> <span class="dv">0</span>)<span class="sc">.</span><span class="bu">sum</span>()<span class="sc">}</span><span class="ss"> of </span><span class="sc">{</span><span class="bu">len</span>(diff)<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb20-43"><a href="#cb20-43" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'  paired t-test       p = </span><span class="sc">{</span>ttest<span class="sc">.</span>pvalue<span class="sc">:.3f}</span><span class="ss">'</span>)</span>
<span id="cb20-44"><a href="#cb20-44" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'</span><span class="ch">\n</span><span class="ss">  -&gt; </span><span class="sc">{</span><span class="st">"NOT significant"</span> <span class="cf">if</span> ttest<span class="sc">.</span>pvalue <span class="op">&gt;</span> <span class="fl">0.05</span> <span class="cf">else</span> <span class="st">"significant"</span><span class="sc">}</span><span class="ss"> at the 5% level: '</span></span>
<span id="cb20-45"><a href="#cb20-45" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f'the single-split gap above does not survive resampling.'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>15 folds (5-fold CV x 3 seeds), mean +/- sd

                               Gamma Deviance               Gini    vs null
Intercept only             1.0428 +/- 0.0324     0.0000 +/- 0.0000   +0.000%
Gamma GLM                  1.0370 +/- 0.0329     0.0999 +/- 0.0231   +0.560%
Gradient boosting          1.0358 +/- 0.0337     0.1063 +/- 0.0222   +0.673%

Gini advantage of boosting over the GLM, measured per fold:
  mean difference   +0.0064 +/- 0.0155
  folds boosting won  11 of 15
  paired t-test       p = 0.143

  -&gt; NOT significant at the 5% level: the single-split gap above does not survive resampling.</code></pre>
</div>
</div>
<p><strong>The advantage does not survive resampling.</strong></p>
<p>Across 15 folds the boosting model’s Gini edge averages <strong>+0.006 ± 0.016</strong>, winning 11 folds of 15, at <strong>p = 0.14</strong>. That is not significant at any conventional threshold, and the standard deviation of the per-fold difference (0.016) is nearly three times the mean difference (0.006) — the spread between folds dwarfs the effect.</p>
<p>So the +0.035 Gini gap on the single split in B.1 was <strong>split luck, not signal</strong>. This is the appendix earning its place: reported from one split, it would have supported “use gradient boosting for severity,” a conclusion the data does not license.</p>
<p>That answers question 2: dropping linearity does not reliably help either. Note also how much larger the fold-to-fold deviance spread (±0.033) is than any gap <em>between</em> models (~0.006) — a useful calibration on how much trust a single severity number deserves, and a reason to treat notebook 03’s and 04’s severity results the same way.</p>
</section>
<section id="b.3-do-the-heavy-tail-specialists-have-anything-to-work-with" class="level4">
<h4 class="anchored" data-anchor-id="b.3-do-the-heavy-tail-specialists-have-anything-to-work-with">B.3 Do the heavy-tail specialists have anything to work with?</h4>
<p>Questions 1 and 2 came back negative, which leaves question 3. Before concluding that the data is the limit, the specialist tools deserve a hearing — the actuarial literature has two main answers for heavy-tailed severity, and neither is in the list above.</p>
<p><strong>Composite (spliced) models.</strong> Model the body and the tail with different distributions: a truncated Gamma GLM below some threshold <span class="math inline">\(u\)</span>, and a <strong>generalised Pareto distribution</strong> above it, fitted by peaks-over-threshold. Extreme value theory justifies this — the Pickands–Balkema–de Haan theorem says exceedances over a high threshold converge to the GPD almost regardless of the underlying distribution, so the tail shape is asymptotically principled rather than assumed. Laudagé, Desmettre and Wenzel (2019) show that when severity really is heavy-tailed, a plain Gamma GLM recovers <em>misleading</em> relationships between tariff features and expected severity, while a threshold model recovers them correctly.</p>
<p><strong>GB2 (generalised beta of the second kind).</strong> A four-parameter family that nests the Gamma, Weibull, Burr Type XII, Pareto and lognormal as special or limiting cases. Rather than choosing a distribution, you let the data choose within a family flexible enough to span light and heavy tails at once.</p>
<p><strong>Both rest on the same premise</strong>, and it is testable directly. Splicing only helps if the rating features tell you <em>which</em> claims land in the tail — otherwise the tail model is fitted to a subset you cannot identify in advance, and at prediction time you have no way to know which regime a policy belongs to. GB2’s extra flexibility is likewise only useful if there is structure for it to find.</p>
<p>So instead of fitting these models, test their premise: <strong>as a classification problem, can the features predict whether a claim will be large?</strong> If the answer is no, neither approach can help, and no amount of tail flexibility will change that. The cell below also runs a <strong>permutation test</strong> — refitting on shuffled targets to establish how much “explained deviance” 42 free parameters manufacture from noise alone — and checks whether the tail is even present in the cleaned data.</p>
<div id="appx-b-premise" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;execution&quot;,&quot;value&quot;:{&quot;iopub.execute_input&quot;:&quot;2026-08-27T15:19:36.701780Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-08-27T15:19:36.701707Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-08-27T15:19:48.743080Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-08-27T15:19:48.742486Z&quot;}}" data-execution_count="12">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ── Do composite / extreme-value models have anything to work with? ─────────</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="co"># A spliced model (light-tailed body + generalised Pareto tail) and the GB2</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="co"># family are the standard actuarial answers to heavy-tailed severity. Both rest</span></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a><span class="co"># on one premise: that the rating features tell you WHICH claims land in the</span></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a><span class="co"># tail. That premise is testable directly, as a classification problem.</span></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.ensemble <span class="im">import</span> HistGradientBoostingClassifier</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.linear_model <span class="im">import</span> LogisticRegression</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.model_selection <span class="im">import</span> cross_val_score, StratifiedKFold</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Can the features predict which claims are large?  (AUC 0.5 = no signal)</span><span class="ch">\n</span><span class="st">'</span>)</span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a>cv <span class="op">=</span> StratifiedKFold(<span class="dv">5</span>, shuffle<span class="op">=</span><span class="va">True</span>, random_state<span class="op">=</span><span class="dv">42</span>)</span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> q <span class="kw">in</span> [<span class="fl">0.90</span>, <span class="fl">0.95</span>, <span class="fl">0.99</span>]:</span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a>    label <span class="op">=</span> (y <span class="op">&gt;</span> y.quantile(q)).astype(<span class="bu">int</span>)</span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a>    a_lr <span class="op">=</span> cross_val_score(LogisticRegression(max_iter<span class="op">=</span><span class="dv">2000</span>), X, label, cv<span class="op">=</span>cv, scoring<span class="op">=</span><span class="st">'roc_auc'</span>)</span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a>    a_gb <span class="op">=</span> cross_val_score(HistGradientBoostingClassifier(random_state<span class="op">=</span><span class="dv">42</span>), X, label, cv<span class="op">=</span>cv, scoring<span class="op">=</span><span class="st">'roc_auc'</span>)</span>
<span id="cb22-16"><a href="#cb22-16" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f'  P(claim &gt; </span><span class="sc">{</span>q<span class="sc">:.0%}</span><span class="ss"> quantile = </span><span class="sc">{</span>y<span class="sc">.</span>quantile(q)<span class="sc">:&gt;8,.0f}</span><span class="ss"> EUR)   '</span></span>
<span id="cb22-17"><a href="#cb22-17" aria-hidden="true" tabindex="-1"></a>          <span class="ss">f'logistic </span><span class="sc">{</span>a_lr<span class="sc">.</span>mean()<span class="sc">:.3f}</span><span class="ss">+/-</span><span class="sc">{</span>a_lr<span class="sc">.</span>std()<span class="sc">:.3f}</span><span class="ss">   boosting </span><span class="sc">{</span>a_gb<span class="sc">.</span>mean()<span class="sc">:.3f}</span><span class="ss">+/-</span><span class="sc">{</span>a_gb<span class="sc">.</span>std()<span class="sc">:.3f}</span><span class="ss">'</span>)</span>
<span id="cb22-18"><a href="#cb22-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-19"><a href="#cb22-19" aria-hidden="true" tabindex="-1"></a><span class="co"># ── How much of the 1.3% deviance explained is just 42 free parameters? ─────</span></span>
<span id="cb22-20"><a href="#cb22-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Refit on shuffled targets: any deviance the model "explains" there is pure</span></span>
<span id="cb22-21"><a href="#cb22-21" aria-hidden="true" tabindex="-1"></a><span class="co"># overfitting, and gives the noise floor the real figure must clear.</span></span>
<span id="cb22-22"><a href="#cb22-22" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'</span><span class="ch">\n</span><span class="st">Permutation test — deviance explained on SHUFFLED targets:</span><span class="ch">\n</span><span class="st">'</span>)</span>
<span id="cb22-23"><a href="#cb22-23" aria-hidden="true" tabindex="-1"></a>observed <span class="op">=</span> <span class="dv">1</span> <span class="op">-</span> result.deviance <span class="op">/</span> result.null_deviance</span>
<span id="cb22-24"><a href="#cb22-24" aria-hidden="true" tabindex="-1"></a>perm <span class="op">=</span> []</span>
<span id="cb22-25"><a href="#cb22-25" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> s <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">20</span>):</span>
<span id="cb22-26"><a href="#cb22-26" aria-hidden="true" tabindex="-1"></a>    ys <span class="op">=</span> y_train.sample(frac<span class="op">=</span><span class="dv">1</span>, random_state<span class="op">=</span>s).values</span>
<span id="cb22-27"><a href="#cb22-27" aria-hidden="true" tabindex="-1"></a>    perm_fit <span class="op">=</span> sm.GLM(ys, X_train_sm, family<span class="op">=</span>sm.families.Gamma(sm.families.links.Log())).fit()</span>
<span id="cb22-28"><a href="#cb22-28" aria-hidden="true" tabindex="-1"></a>    perm.append(<span class="dv">1</span> <span class="op">-</span> perm_fit.deviance <span class="op">/</span> perm_fit.null_deviance)</span>
<span id="cb22-29"><a href="#cb22-29" aria-hidden="true" tabindex="-1"></a>perm <span class="op">=</span> np.array(perm)</span>
<span id="cb22-30"><a href="#cb22-30" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'  observed (real targets)      </span><span class="sc">{</span>observed<span class="sc">:.4%}</span><span class="ss">'</span>)</span>
<span id="cb22-31"><a href="#cb22-31" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'  permuted, 20 reps            </span><span class="sc">{</span>perm<span class="sc">.</span>mean()<span class="sc">:.4%}</span><span class="ss"> +/- </span><span class="sc">{</span>perm<span class="sc">.</span>std()<span class="sc">:.4%}</span><span class="ss">   (max </span><span class="sc">{</span>perm<span class="sc">.</span><span class="bu">max</span>()<span class="sc">:.4%}</span><span class="ss">)'</span>)</span>
<span id="cb22-32"><a href="#cb22-32" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'  -&gt; genuine signal            </span><span class="sc">{</span>observed <span class="op">-</span> perm<span class="sc">.</span>mean()<span class="sc">:.4%}</span><span class="ss"> once the fitting artefact is removed'</span>)</span>
<span id="cb22-33"><a href="#cb22-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-34"><a href="#cb22-34" aria-hidden="true" tabindex="-1"></a><span class="co"># ── Has the tail already been removed upstream? ─────────────────────────────</span></span>
<span id="cb22-35"><a href="#cb22-35" aria-hidden="true" tabindex="-1"></a>raw <span class="op">=</span> df[<span class="st">'ClaimAmount'</span>]</span>
<span id="cb22-36"><a href="#cb22-36" aria-hidden="true" tabindex="-1"></a>at_max <span class="op">=</span> (raw <span class="op">&gt;=</span> raw.<span class="bu">max</span>() <span class="op">-</span> <span class="dv">1</span>).<span class="bu">sum</span>()</span>
<span id="cb22-37"><a href="#cb22-37" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'</span><span class="ch">\n</span><span class="ss">Tail check on claims_cleaned.csv:'</span>)</span>
<span id="cb22-38"><a href="#cb22-38" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'  max claim </span><span class="sc">{</span>raw<span class="sc">.</span><span class="bu">max</span>()<span class="sc">:,.0f}</span><span class="ss"> EUR | p99 </span><span class="sc">{</span>raw<span class="sc">.</span>quantile(<span class="fl">0.99</span>)<span class="sc">:,.0f}</span><span class="ss"> | p99.9 </span><span class="sc">{</span>raw<span class="sc">.</span>quantile(<span class="fl">0.999</span>)<span class="sc">:,.0f}</span><span class="ss">'</span>)</span>
<span id="cb22-39"><a href="#cb22-39" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'  claims sitting AT the maximum: </span><span class="sc">{</span>at_max<span class="sc">:,}</span><span class="ss"> (</span><span class="sc">{</span>at_max<span class="op">/</span><span class="bu">len</span>(raw)<span class="sc">:.2%}</span><span class="ss"> of claims, '</span></span>
<span id="cb22-40"><a href="#cb22-40" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f'</span><span class="sc">{</span>raw[raw <span class="op">&gt;=</span> raw.<span class="bu">max</span>()<span class="op">-</span><span class="dv">1</span>]<span class="sc">.</span><span class="bu">sum</span>()<span class="op">/</span>raw<span class="sc">.</span><span class="bu">sum</span>()<span class="sc">:.1%}</span><span class="ss"> of total claim cost)'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Can the features predict which claims are large?  (AUC 0.5 = no signal)

  P(claim &gt; 90% quantile =    2,768 EUR)   logistic 0.565+/-0.017   boosting 0.569+/-0.018
  P(claim &gt; 95% quantile =    4,767 EUR)   logistic 0.577+/-0.014   boosting 0.569+/-0.012
  P(claim &gt; 99% quantile =   16,422 EUR)   logistic 0.487+/-0.034   boosting 0.512+/-0.043

Permutation test — deviance explained on SHUFFLED targets:

  observed (real targets)      1.2970%
  permuted, 20 reps            0.3735% +/- 0.0946%   (max 0.6219%)
  -&gt; genuine signal            0.9236% once the fitting artefact is removed

Tail check on claims_cleaned.csv:
  max claim 16,451 EUR | p99 16,422 | p99.9 16,451
  claims sitting AT the maximum: 265 (1.00% of claims, 10.5% of total claim cost)</code></pre>
</div>
</div>
<p><strong>All three checks point the same way.</strong></p>
<p><strong>Tail membership is close to unpredictable.</strong> AUC is 0.565–0.577 for the 90th and 95th percentile thresholds — weak but real — and <strong>0.487–0.512 at the 99th percentile</strong>, which is chance. A coin flip. The premise of a composite model fails exactly where a composite model would operate: at the extreme tail. There is nothing to splice on, and GB2’s extra shape parameters would have no structure to find.</p>
<p><strong>Most of the “explained” deviance is a fitting artefact.</strong> The model explains 1.297% of deviance on the training set — but on <em>shuffled</em> targets, where no relationship can exist by construction, 42 free parameters still manufacture 0.374% ± 0.095%. Subtracting the noise floor leaves roughly <strong>0.92% of genuine signal</strong>. It clears the floor comfortably enough to be real, but that is the entire budget available to any model.</p>
<p><strong>And the tail has already been removed upstream.</strong> 265 claims — 1.00% of the data, but <strong>10.5% of total claim cost</strong> — sit at exactly €16,451, the 99th-percentile cap applied in notebook 01. The p99.9 equals the maximum. Whatever tail behaviour existed in the raw data was winsorized away before this notebook loaded it, which makes extreme value methods doubly inapplicable here: no identifiable tail membership, and no tail left to model.</p>
<hr>
</section>
<section id="b.4-conclusion-the-data-is-the-constraint" class="level4">
<h4 class="anchored" data-anchor-id="b.4-conclusion-the-data-is-the-constraint">B.4 Conclusion: the data is the constraint</h4>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Question</th>
<th>Test</th>
<th>Verdict</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Wrong error distribution?</td>
<td>Six families, same linear predictor</td>
<td><strong>No</strong> — all within 0.03pp</td>
</tr>
<tr class="even">
<td>Wrong mean function?</td>
<td>Gradient boosting, 15-fold paired CV</td>
<td><strong>No</strong> — +0.006 Gini, p = 0.14</td>
</tr>
<tr class="odd">
<td>Heavy-tail specialist needed?</td>
<td>Tail-membership AUC</td>
<td><strong>No premise</strong> — AUC 0.49 at p99</td>
</tr>
<tr class="even">
<td>Is there signal at all?</td>
<td>Permutation test</td>
<td><strong>~0.92%</strong>, and that is the ceiling</td>
</tr>
</tbody>
</table>
<p>The Gamma GLM is retained — not because it beat the alternatives on accuracy, but because <strong>nothing beats anything here</strong>, and when predictive performance is tied the decision falls entirely to the secondary criteria: interpretable multiplicative rating factors, a variance assumption that matches proportional error, guaranteed positivity, and the lowest regulatory documentation burden of any candidate. That is a defensible basis for the choice, and a more honest one than an accuracy claim the data does not support.</p>
<p>The wider result is that <strong>severity here is data-limited, not model-limited</strong>. This matches the published literature on this dataset, where near-zero out-of-sample <span class="math inline">\(R^2\)</span> for severity is a documented property rather than a symptom of a bug: explainable boosting machines tie XGBoost, phase-type regression with Gamma, Pareto and Weibull tails gives MSE 3.66 / 3.69 / 3.70, and pseudo-<span class="math inline">\(R^2\)</span> comes out “broadly the same for all algorithms.”</p>
<p><strong>Three consequences carried forward:</strong></p>
<ol type="1">
<li><strong>Notebooks 03 and 04 should not be expected to improve severity.</strong> Their value is in <em>frequency</em>, which does have exploitable structure. If their severity metrics do move noticeably, suspect the pipeline before believing the gain — and check it against the ±0.033 fold-to-fold spread measured in B.2.</li>
<li><strong>Judge the models on pure premium lift, not severity metrics.</strong> Frequency carries the signal, so the ranking of the frequency × severity product is what has commercial meaning. That is what notebook 05 builds.</li>
<li><strong>The cap is a pricing decision, not just data cleaning.</strong> Capping at the 99th percentile sets aside 10.5% of total claim cost. In practice that layer is priced collectively as a portfolio loading rather than per-policy — which is the correct treatment given that tail membership is unpredictable, but it should be a deliberate choice, stated as such, rather than an artefact of a cleaning step.</li>
</ol>
<hr>
</section>
</section>
</section>
<section id="part-2-frequency-poisson-glm" class="level2">
<h2 class="anchored" data-anchor-id="part-2-frequency-poisson-glm">Part 2: Frequency — Poisson GLM</h2>
<p><em>Predicts the probability of a claim occurring. Uses the full 678k policies dataset.</em></p>
<p><strong>Why Poisson?</strong> Claim counts are non-negative integers — the Poisson distribution is the standard actuarial choice for modelling count data. The log-link ensures predictions are always positive.</p>
<p><strong>Exposure offset:</strong> Policies have different durations (Exposure column, in years). A policy active for 0.5 years has half the opportunity to claim. We account for this by including log(Exposure) as an offset in the model.</p>
<section id="load-prepare-data" class="level3">
<h3 class="anchored" data-anchor-id="load-prepare-data">2.1 Load &amp; Prepare Data</h3>
<div id="auxwzlbxs48" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;execution&quot;,&quot;value&quot;:{&quot;iopub.execute_input&quot;:&quot;2026-08-27T15:19:48.745078Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-08-27T15:19:48.744974Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-08-27T15:19:48.978713Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-08-27T15:19:48.978423Z&quot;}}" data-execution_count="13">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load policies_cleaned.csv from the data folder</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>df_freq <span class="op">=</span> pd.read_csv(<span class="st">'../data/policies_cleaned.csv'</span>)</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(df_freq.shape)</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>df_freq.head()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>(678013, 15)</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="13">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">IDpol</th>
<th data-quarto-table-cell-role="th">ClaimNb</th>
<th data-quarto-table-cell-role="th">Exposure</th>
<th data-quarto-table-cell-role="th">Area</th>
<th data-quarto-table-cell-role="th">VehPower</th>
<th data-quarto-table-cell-role="th">VehAge</th>
<th data-quarto-table-cell-role="th">DrivAge</th>
<th data-quarto-table-cell-role="th">BonusMalus</th>
<th data-quarto-table-cell-role="th">VehBrand</th>
<th data-quarto-table-cell-role="th">VehGas</th>
<th data-quarto-table-cell-role="th">Density</th>
<th data-quarto-table-cell-role="th">Region</th>
<th data-quarto-table-cell-role="th">HasClaim</th>
<th data-quarto-table-cell-role="th">DrivAge_bin</th>
<th data-quarto-table-cell-role="th">BonusMalus_bin</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>1.0</td>
<td>1</td>
<td>0.10</td>
<td>D</td>
<td>5</td>
<td>0</td>
<td>55</td>
<td>50</td>
<td>B12</td>
<td>'Regular'</td>
<td>1217</td>
<td>R82</td>
<td>1</td>
<td>46-55</td>
<td>50-60</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>3.0</td>
<td>1</td>
<td>0.77</td>
<td>D</td>
<td>5</td>
<td>0</td>
<td>55</td>
<td>50</td>
<td>B12</td>
<td>'Regular'</td>
<td>1217</td>
<td>R82</td>
<td>1</td>
<td>46-55</td>
<td>50-60</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>5.0</td>
<td>1</td>
<td>0.75</td>
<td>B</td>
<td>6</td>
<td>2</td>
<td>52</td>
<td>50</td>
<td>B12</td>
<td>'Diesel'</td>
<td>54</td>
<td>R22</td>
<td>1</td>
<td>46-55</td>
<td>50-60</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>10.0</td>
<td>1</td>
<td>0.09</td>
<td>B</td>
<td>7</td>
<td>0</td>
<td>46</td>
<td>50</td>
<td>B12</td>
<td>'Diesel'</td>
<td>76</td>
<td>R72</td>
<td>1</td>
<td>46-55</td>
<td>50-60</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>11.0</td>
<td>1</td>
<td>0.84</td>
<td>B</td>
<td>7</td>
<td>0</td>
<td>46</td>
<td>50</td>
<td>B12</td>
<td>'Diesel'</td>
<td>76</td>
<td>R72</td>
<td>1</td>
<td>46-55</td>
<td>50-60</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="bojrro7ixqv" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;execution&quot;,&quot;value&quot;:{&quot;iopub.execute_input&quot;:&quot;2026-08-27T15:19:48.979790Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-08-27T15:19:48.979729Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-08-27T15:19:49.205469Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-08-27T15:19:49.205133Z&quot;}}" data-execution_count="14">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>features_freq <span class="op">=</span> [<span class="st">'VehPower'</span>, <span class="st">'VehAge'</span>, <span class="st">'DrivAge'</span>, <span class="st">'BonusMalus'</span>, <span class="st">'Density'</span>, <span class="st">'Area'</span>, <span class="st">'VehBrand'</span>, <span class="st">'VehGas'</span>, <span class="st">'Region'</span>]</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>target_freq <span class="op">=</span> <span class="st">'ClaimNb'</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a><span class="co"># one-hot encode categorical columns and convert to float (same as severity section)</span></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>df_freq_model <span class="op">=</span> pd.get_dummies(df_freq[features_freq <span class="op">+</span> [target_freq]], columns<span class="op">=</span>[<span class="st">'Area'</span>, <span class="st">'VehBrand'</span>, <span class="st">'VehGas'</span>, <span class="st">'Region'</span>], drop_first<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>df_freq_model <span class="op">=</span> df_freq_model.astype(<span class="bu">float</span>)</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Separate out exposure before dropping — needed as offset</span></span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>exposure <span class="op">=</span> df_freq[<span class="st">'Exposure'</span>]</span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a>X_freq <span class="op">=</span> df_freq_model.drop(columns<span class="op">=</span>[target_freq])</span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a>y_freq <span class="op">=</span> df_freq_model[target_freq]</span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-14"><a href="#cb26-14" aria-hidden="true" tabindex="-1"></a><span class="co"># train/test split (80/20, random_state=42)</span></span>
<span id="cb26-15"><a href="#cb26-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Make sure to split exposure with the same indices</span></span>
<span id="cb26-16"><a href="#cb26-16" aria-hidden="true" tabindex="-1"></a>X_freq_train, X_freq_test, y_freq_train, y_freq_test, exp_train, exp_test <span class="op">=</span> train_test_split(X_freq, y_freq, exposure, test_size<span class="op">=</span><span class="fl">0.2</span>, random_state<span class="op">=</span><span class="dv">42</span>)</span>
<span id="cb26-17"><a href="#cb26-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-18"><a href="#cb26-18" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Train: </span><span class="sc">{</span>X_freq_train<span class="sc">.</span>shape<span class="sc">}</span><span class="ss">, Test: </span><span class="sc">{</span>X_freq_test<span class="sc">.</span>shape<span class="sc">}</span><span class="ss">'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Train: (542410, 42), Test: (135603, 42)</code></pre>
</div>
</div>
</section>
<section id="fit-poisson-glm" class="level3">
<h3 class="anchored" data-anchor-id="fit-poisson-glm">2.2 Fit Poisson GLM</h3>
<div id="ax6lvc964b" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;execution&quot;,&quot;value&quot;:{&quot;iopub.execute_input&quot;:&quot;2026-08-27T15:19:49.206592Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-08-27T15:19:49.206534Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-08-27T15:19:51.978382Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-08-27T15:19:51.977872Z&quot;}}" data-execution_count="15">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>X_freq_train_sm <span class="op">=</span> sm.add_constant(X_freq_train)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>X_freq_test_sm  <span class="op">=</span> sm.add_constant(X_freq_test)</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Poisson GLM with log-link and log(Exposure) as an offset.</span></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a><span class="co"># The offset must be supplied at FIT time, not only at predict time: it fixes the</span></span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a><span class="co"># exposure coefficient at 1, which is what turns this from a model of claim</span></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a><span class="co"># *counts* into a model of claim *rates*. Fitting without it and predicting with</span></span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a><span class="co"># it estimates coefficients on the wrong scale.</span></span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>result_freq <span class="op">=</span> sm.GLM(</span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a>    y_freq_train,</span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a>    X_freq_train_sm,</span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a>    family<span class="op">=</span>sm.families.Poisson(link<span class="op">=</span>sm.families.links.Log()),</span>
<span id="cb28-13"><a href="#cb28-13" aria-hidden="true" tabindex="-1"></a>    offset<span class="op">=</span>np.log(exp_train)</span>
<span id="cb28-14"><a href="#cb28-14" aria-hidden="true" tabindex="-1"></a>).fit()</span>
<span id="cb28-15"><a href="#cb28-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-16"><a href="#cb28-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(result_freq.summary())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                 Generalized Linear Model Regression Results                  
==============================================================================
Dep. Variable:                ClaimNb   No. Observations:               542410
Model:                            GLM   Df Residuals:                   542367
Model Family:                 Poisson   Df Model:                           42
Link Function:                    Log   Scale:                          1.0000
Method:                          IRLS   Log-Likelihood:            -1.1426e+05
Date:                Fri, 28 Aug 2026   Deviance:                   1.7314e+05
Time:                        01:19:51   Pearson chi2:                 1.36e+06
No. Iterations:                     7   Pseudo R-squ. (CS):            0.01077
Covariance Type:            nonrobust                                         
====================================================================================
                       coef    std err          z      P&gt;|z|      [0.025      0.975]
------------------------------------------------------------------------------------
const               -4.0107      0.052    -77.132      0.000      -4.113      -3.909
VehPower             0.0155      0.003      5.009      0.000       0.009       0.022
VehAge              -0.0390      0.001    -29.797      0.000      -0.042      -0.036
DrivAge              0.0068      0.000     15.475      0.000       0.006       0.008
BonusMalus           0.0226      0.000     66.033      0.000       0.022       0.023
Density          -8.726e-07   4.14e-06     -0.211      0.833   -8.98e-06    7.24e-06
Area_B               0.0609      0.024      2.504      0.012       0.013       0.109
Area_C               0.0936      0.020      4.633      0.000       0.054       0.133
Area_D               0.1838      0.022      8.469      0.000       0.141       0.226
Area_E               0.2322      0.029      8.095      0.000       0.176       0.288
Area_F               0.2305      0.100      2.296      0.022       0.034       0.427
VehBrand_B10        -0.0372      0.042     -0.891      0.373      -0.119       0.045
VehBrand_B11         0.0313      0.045      0.691      0.489      -0.057       0.120
VehBrand_B12         0.1679      0.020      8.592      0.000       0.130       0.206
VehBrand_B13         0.0097      0.046      0.209      0.835      -0.081       0.100
VehBrand_B14        -0.2019      0.090     -2.235      0.025      -0.379      -0.025
VehBrand_B2         -0.0093      0.017     -0.547      0.584      -0.043       0.024
VehBrand_B3         -0.0284      0.025     -1.153      0.249      -0.077       0.020
VehBrand_B4         -0.0314      0.033     -0.942      0.346      -0.097       0.034
VehBrand_B5          0.0825      0.028      2.993      0.003       0.028       0.137
VehBrand_B6         -0.0479      0.032     -1.508      0.131      -0.110       0.014
VehGas_'Regular'     0.0502      0.012      4.099      0.000       0.026       0.074
Region_R21           0.0964      0.093      1.040      0.298      -0.085       0.278
Region_R22           0.0738      0.057      1.291      0.197      -0.038       0.186
Region_R23          -0.0448      0.068     -0.661      0.508      -0.177       0.088
Region_R24           0.0777      0.027      2.833      0.005       0.024       0.132
Region_R25          -0.0049      0.051     -0.098      0.922      -0.104       0.094
Region_R26           0.0352      0.054      0.655      0.512      -0.070       0.141
Region_R31          -0.0873      0.039     -2.218      0.027      -0.164      -0.010
Region_R41          -0.2524      0.051     -4.926      0.000      -0.353      -0.152
Region_R42          -0.0392      0.100     -0.390      0.697      -0.236       0.158
Region_R43          -0.1248      0.156     -0.800      0.424      -0.431       0.181
Region_R52           0.0056      0.034      0.165      0.869      -0.061       0.072
Region_R53           0.0920      0.032      2.850      0.004       0.029       0.155
Region_R54          -0.0313      0.043     -0.724      0.469      -0.116       0.053
Region_R72          -0.1162      0.038     -3.039      0.002      -0.191      -0.041
Region_R73          -0.1067      0.048     -2.229      0.026      -0.201      -0.013
Region_R74           0.1510      0.075      2.006      0.045       0.003       0.298
Region_R82           0.0947      0.027      3.490      0.000       0.041       0.148
Region_R83          -0.2705      0.083     -3.240      0.001      -0.434      -0.107
Region_R91          -0.0258      0.037     -0.699      0.484      -0.098       0.046
Region_R93          -0.0006      0.028     -0.021      0.983      -0.056       0.055
Region_R94           0.1147      0.075      1.536      0.125      -0.032       0.261
====================================================================================</code></pre>
</div>
</div>
<p>Significant predictors (all p &lt; 0.001). - BonusMalus (positive, strongest): higher claims history score leads to more claims. Coefficient of 0.0178 means each point increase multiplies expected claim frequency by <span class="math inline">\(e^{0.017} = 1.018\)</span>.<br>
- DrivAge (positive): older drivers claim slightly more often in this dataset, which seems counterintuitive. Likely confounded by exposure or policy mix.<br>
- VehAge (negative): newer vehicles claim more frequently, possibly because they are driven more.<br>
- Area D and E (positive): higher claim rates in those areas, consistent with the EDA findings.</p>
<p>Compared to the severity model. - Much stronger signal overall. BonusMalus and DrivAge are highly significant here but were weak in the severity<br>
model.<br>
- Pseudo R² of 0.006 is similar, but with 542k observations the z-scores are much larger, meaning we can detect smaller real effects.</p>
</section>
<section id="evaluate-on-test-set-1" class="level3">
<h3 class="anchored" data-anchor-id="evaluate-on-test-set-1">2.3 Evaluate on Test Set</h3>
<div id="i90cogxg8sp" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;execution&quot;,&quot;value&quot;:{&quot;iopub.execute_input&quot;:&quot;2026-08-27T15:19:51.980787Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-08-27T15:19:51.980686Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-08-27T15:19:51.996103Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-08-27T15:19:51.995662Z&quot;}}" data-execution_count="16">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># </span><span class="al">TODO</span><span class="co">: generate predictions on the test set</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Remember to pass offset=np.log(exp_test) when predicting</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>y_freq_pred <span class="op">=</span> result_freq.predict(X_freq_test_sm, offset<span class="op">=</span>np.log(exp_test))</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>mae_freq  <span class="op">=</span> mean_absolute_error(y_freq_test, y_freq_pred)</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>rmse_freq <span class="op">=</span> mean_squared_error(y_freq_test, y_freq_pred) <span class="op">**</span> <span class="fl">0.5</span></span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Poisson deviance — correct metric for count models</span></span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> poisson_deviance(y_true, y_pred):</span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a>    y_pred <span class="op">=</span> np.clip(y_pred, <span class="fl">1e-10</span>, <span class="va">None</span>)</span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="dv">2</span> <span class="op">*</span> np.<span class="bu">sum</span>(y_true <span class="op">*</span> np.log(np.where(y_true <span class="op">==</span> <span class="dv">0</span>, <span class="dv">1</span>, y_true <span class="op">/</span> y_pred)) <span class="op">-</span> (y_true <span class="op">-</span> y_pred))</span>
<span id="cb30-12"><a href="#cb30-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-13"><a href="#cb30-13" aria-hidden="true" tabindex="-1"></a>pd_score <span class="op">=</span> poisson_deviance(y_freq_test.values, y_freq_pred)</span>
<span id="cb30-14"><a href="#cb30-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-15"><a href="#cb30-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'--- Poisson GLM Test Set Performance ---'</span>)</span>
<span id="cb30-16"><a href="#cb30-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'MAE:               </span><span class="sc">{</span>mae_freq<span class="sc">:.4f}</span><span class="ss">'</span>)</span>
<span id="cb30-17"><a href="#cb30-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'RMSE:              </span><span class="sc">{</span>rmse_freq<span class="sc">:.4f}</span><span class="ss">'</span>)</span>
<span id="cb30-18"><a href="#cb30-18" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Poisson Deviance:  </span><span class="sc">{</span>pd_score<span class="sc">:.2f}</span><span class="ss">'</span>)</span>
<span id="cb30-19"><a href="#cb30-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-20"><a href="#cb30-20" aria-hidden="true" tabindex="-1"></a>glm_freq_metrics <span class="op">=</span> {<span class="st">'model'</span>: <span class="st">'GLM'</span>, <span class="st">'MAE'</span>: mae_freq, <span class="st">'RMSE'</span>: rmse_freq, <span class="st">'PoissonDeviance'</span>: pd_score}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>--- Poisson GLM Test Set Performance ---
MAE:               0.0988
RMSE:              0.2370
Poisson Deviance:  43585.73</code></pre>
</div>
</div>
<ul>
<li>MAE of 0.077 means predictions are on average 0.077 claims off. Given the overall claim rate is 5.0%, this is reasonable.
<ul>
<li>RMSE of 0.238 is higher due to the large number of zero-claim policies pulling predictions away from actuals.</li>
<li>Poisson Deviance of 46,566 is a large absolute number but that is expected with 135k test records. It is more useful for comparison against XGBoost and the neural net later.</li>
</ul></li>
</ul>
<div id="870303a4" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;execution&quot;,&quot;value&quot;:{&quot;iopub.execute_input&quot;:&quot;2026-08-27T15:19:51.997100Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-08-27T15:19:51.997040Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-08-27T15:19:52.358141Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-08-27T15:19:52.357664Z&quot;}}" data-execution_count="17">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">14</span>, <span class="dv">5</span>))                                                                       </span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Get predictions on full training + test set for this analysis                                                       </span></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>X_all_sm <span class="op">=</span> sm.add_constant(pd.concat([X_freq_train, X_freq_test]))</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>exp_all <span class="op">=</span> pd.concat([exp_train, exp_test])</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>df_freq[<span class="st">'predicted_rate'</span>] <span class="op">=</span> result_freq.predict(X_all_sm, offset<span class="op">=</span>np.log(exp_all))</span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>df_freq[<span class="st">'HasClaim'</span>] <span class="op">=</span> (df_freq[<span class="st">'ClaimNb'</span>] <span class="op">!=</span> <span class="dv">0</span>).astype(<span class="bu">int</span>)</span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a>df_freq[<span class="st">'actual_rate'</span>] <span class="op">=</span> df_freq[<span class="st">'HasClaim'</span>]</span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a><span class="co"># BonusMalus</span></span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a>bm_bins <span class="op">=</span> pd.cut(df_freq[<span class="st">'BonusMalus'</span>], bins<span class="op">=</span>[<span class="dv">49</span>,<span class="dv">60</span>,<span class="dv">80</span>,<span class="dv">100</span>,<span class="dv">150</span>,<span class="dv">230</span>],</span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a>labels<span class="op">=</span>[<span class="st">'50-60'</span>,<span class="st">'61-80'</span>,<span class="st">'81-100'</span>,<span class="st">'101-150'</span>,<span class="st">'150+'</span>])</span>
<span id="cb32-13"><a href="#cb32-13" aria-hidden="true" tabindex="-1"></a>actual_bm <span class="op">=</span> df_freq.groupby(bm_bins)[<span class="st">'actual_rate'</span>].mean()</span>
<span id="cb32-14"><a href="#cb32-14" aria-hidden="true" tabindex="-1"></a>pred_bm <span class="op">=</span> df_freq.groupby(bm_bins)[<span class="st">'predicted_rate'</span>].mean()</span>
<span id="cb32-15"><a href="#cb32-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-16"><a href="#cb32-16" aria-hidden="true" tabindex="-1"></a>x <span class="op">=</span> <span class="bu">range</span>(<span class="bu">len</span>(actual_bm))</span>
<span id="cb32-17"><a href="#cb32-17" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].bar(x, actual_bm, width<span class="op">=</span><span class="fl">0.4</span>, label<span class="op">=</span><span class="st">'Actual'</span>, align<span class="op">=</span><span class="st">'center'</span>)                                                  </span>
<span id="cb32-18"><a href="#cb32-18" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].bar([i <span class="op">+</span> <span class="fl">0.4</span> <span class="cf">for</span> i <span class="kw">in</span> x], pred_bm, width<span class="op">=</span><span class="fl">0.4</span>, label<span class="op">=</span><span class="st">'Predicted'</span>, align<span class="op">=</span><span class="st">'center'</span>)                              </span>
<span id="cb32-19"><a href="#cb32-19" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_xticks([i <span class="op">+</span> <span class="fl">0.2</span> <span class="cf">for</span> i <span class="kw">in</span> x])                                                                              </span>
<span id="cb32-20"><a href="#cb32-20" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_xticklabels(actual_bm.index)                                                                              </span>
<span id="cb32-21"><a href="#cb32-21" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_title(<span class="st">'Claim Rate by BonusMalus'</span>)                                                                         </span>
<span id="cb32-22"><a href="#cb32-22" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_ylabel(<span class="st">'Claim Rate'</span>)                          </span>
<span id="cb32-23"><a href="#cb32-23" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].legend()                                                                                                      </span>
<span id="cb32-24"><a href="#cb32-24" aria-hidden="true" tabindex="-1"></a>                                                                                                                    </span>
<span id="cb32-25"><a href="#cb32-25" aria-hidden="true" tabindex="-1"></a><span class="co"># DrivAge</span></span>
<span id="cb32-26"><a href="#cb32-26" aria-hidden="true" tabindex="-1"></a>age_bins <span class="op">=</span> pd.cut(df_freq[<span class="st">'DrivAge'</span>], bins<span class="op">=</span>[<span class="dv">17</span>,<span class="dv">25</span>,<span class="dv">35</span>,<span class="dv">45</span>,<span class="dv">55</span>,<span class="dv">65</span>,<span class="dv">100</span>],                                                   </span>
<span id="cb32-27"><a href="#cb32-27" aria-hidden="true" tabindex="-1"></a>labels<span class="op">=</span>[<span class="st">'18-25'</span>,<span class="st">'26-35'</span>,<span class="st">'36-45'</span>,<span class="st">'46-55'</span>,<span class="st">'56-65'</span>,<span class="st">'65+'</span>])                                                               </span>
<span id="cb32-28"><a href="#cb32-28" aria-hidden="true" tabindex="-1"></a>actual_age <span class="op">=</span> df_freq.groupby(age_bins)[<span class="st">'actual_rate'</span>].mean()</span>
<span id="cb32-29"><a href="#cb32-29" aria-hidden="true" tabindex="-1"></a>pred_age <span class="op">=</span> df_freq.groupby(age_bins)[<span class="st">'predicted_rate'</span>].mean()                                                         </span>
<span id="cb32-30"><a href="#cb32-30" aria-hidden="true" tabindex="-1"></a>                                                        </span>
<span id="cb32-31"><a href="#cb32-31" aria-hidden="true" tabindex="-1"></a>x <span class="op">=</span> <span class="bu">range</span>(<span class="bu">len</span>(actual_age))                                                                                            </span>
<span id="cb32-32"><a href="#cb32-32" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].bar(x, actual_age, width<span class="op">=</span><span class="fl">0.4</span>, label<span class="op">=</span><span class="st">'Actual'</span>, align<span class="op">=</span><span class="st">'center'</span>)</span>
<span id="cb32-33"><a href="#cb32-33" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].bar([i <span class="op">+</span> <span class="fl">0.4</span> <span class="cf">for</span> i <span class="kw">in</span> x], pred_age, width<span class="op">=</span><span class="fl">0.4</span>, label<span class="op">=</span><span class="st">'Predicted'</span>, align<span class="op">=</span><span class="st">'center'</span>)                             </span>
<span id="cb32-34"><a href="#cb32-34" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_xticks([i <span class="op">+</span> <span class="fl">0.2</span> <span class="cf">for</span> i <span class="kw">in</span> x])</span>
<span id="cb32-35"><a href="#cb32-35" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_xticklabels(actual_age.index)                                                                             </span>
<span id="cb32-36"><a href="#cb32-36" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_title(<span class="st">'Claim Rate by DrivAge'</span>)                                                                            </span>
<span id="cb32-37"><a href="#cb32-37" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_ylabel(<span class="st">'Claim Rate'</span>)</span>
<span id="cb32-38"><a href="#cb32-38" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].legend()                                                                                                      </span>
<span id="cb32-39"><a href="#cb32-39" aria-hidden="true" tabindex="-1"></a>                                                        </span>
<span id="cb32-40"><a href="#cb32-40" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb32-41"><a href="#cb32-41" aria-hidden="true" tabindex="-1"></a>plt.savefig(<span class="st">'../results/04_freq_actual_vs_predicted.png'</span>, dpi<span class="op">=</span><span class="dv">150</span>, bbox_inches<span class="op">=</span><span class="st">'tight'</span>)</span>
<span id="cb32-42"><a href="#cb32-42" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="02_glm_files/figure-html/cell-18-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p><strong>BonusMalus (left)</strong></p>
<p>The model correctly captures the upward trend. Predicted rates rise monotonically as BonusMalus increases, which reflects the coefficient being positive and significant in the GLM summary.</p>
<p>However the model consistently underpredicts across all bins, and the magnitude of underprediction varies considerably. For the three lowest risk bins (50-60, 61-80, 81-100) predictions sit around 0.025-0.030 while actual rates range from 0.046 to 0.065. This is a systematic underestimate of roughly 50-60% in these groups. The model performs best at the highest risk band (150+) where predicted 0.158 is close to actual 0.191, a gap of around 17%.</p>
<p>This compression toward the mean is a known limitation of GLMs with few features. The model cannot fully separate the cleanest drivers from average-risk drivers because BonusMalus alone, as a linear term, does not carry enough discriminating power at the lower end of the range. In practice actuaries often apply credibility adjustments or add interaction terms to address this.</p>
<p><strong>DrivAge (right)</strong></p>
<p>Young drivers (18-25) are clearly the highest risk group at 0.068. Rates drop sharply into the mid-twenties, remain relatively stable through middle age at around 0.043-0.055, then rise modestly for the 65+ group to 0.059.</p>
<p>The GLM substantially underpredicts all age groups, with predictions ranging only from 0.023 to 0.046. More importantly it fails to capture the non-linear shape of the relationship. The model predicts a gentle upward slope across age groups rather than the sharp peak at 18-25 and the moderate elevation at 65+. Middle-aged drivers (26-45) are the least risky in reality but the model assigns them almost the same predicted rate as older drivers.</p>
<p>This is a direct consequence of the GLM treating DrivAge as a linear predictor. The actual relationship requires at minimum a quadratic term or binned age categories to fit properly. This is precisely the limitation XGBoost will address since tree-based models find non-linear splits automatically. We would expect XGBoost to much better separate the 18-25 group from the rest and to correctly identify the modest uptick at 65+.</p>
<p><strong>Overall</strong></p>
<p>Both charts point to the same underlying issue. The Poisson GLM captures the direction of relationships correctly but compresses predictions toward the mean and misses non-linearities. This is expected for a baseline model. The Poisson deviance of 46,581 and the calibration gaps here set the benchmark that XGBoost and the neural network will be judged against.</p>
<hr>
</section>
</section>
<section id="save-models-predictions-and-metrics" class="level2">
<h2 class="anchored" data-anchor-id="save-models-predictions-and-metrics">6. Save Models, Predictions and Metrics</h2>
<p>Notebook 5 is a pure comparison notebook — it must not refit anything. Everything it needs is written here: the fitted models, the test-set predictions, and the metrics.</p>
<p>This cell also writes <code>results/test_split.npz</code>, the <strong>shared definition of the test set</strong>. Notebooks 3 and 4 reproduce the same split from the same seed, but notebook 5 should never have to touch the raw CSVs or re-derive a split just to know which rows it is looking at.</p>
<p>One detail matters for notebook 5’s pure premium calculation. Pure premium is frequency × severity <em>for the same policy</em>, so we need the severity model’s prediction on the <strong>frequency</strong> test rows, not just the severity test rows. That is <code>sev_on_freq_test</code> below. Computing it here — from <code>X_freq_test</code> directly — guarantees it stays aligned with <code>freq_test_rate</code>. (Deriving it downstream by positional slicing silently misaligns the two, because <code>train_test_split</code> shuffles.)</p>
<div id="ca9aabcc" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;execution&quot;,&quot;value&quot;:{&quot;iopub.execute_input&quot;:&quot;2026-08-27T15:19:52.359266Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-08-27T15:19:52.359179Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-08-27T15:19:52.519831Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-08-27T15:19:52.519419Z&quot;}}" data-execution_count="18">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> json, pickle</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a><span class="co"># The severity and frequency design matrices share identical columns in identical</span></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a><span class="co"># order, so the severity model can be scored directly on the frequency test rows.</span></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a><span class="cf">assert</span> <span class="bu">list</span>(X_test.columns) <span class="op">==</span> <span class="bu">list</span>(X_freq_test.columns), <span class="st">'design matrices misaligned'</span></span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Severity GLM applied to the frequency test policies — the severity half of pure premium</span></span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>sev_on_freq_test <span class="op">=</span> result.predict(sm.add_constant(X_freq_test))</span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a><span class="co"># ── Models ───────────────────────────────────────────────────────────────────</span></span>
<span id="cb33-11"><a href="#cb33-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Pickled as plain coefficient arrays (order: const, then X_train.columns) rather</span></span>
<span id="cb33-12"><a href="#cb33-12" aria-hidden="true" tabindex="-1"></a><span class="co"># than via GLMResultsWrapper.save(), which embeds the full training design matrix</span></span>
<span id="cb33-13"><a href="#cb33-13" aria-hidden="true" tabindex="-1"></a><span class="co"># (~400MB) that the dashboard never needs.</span></span>
<span id="cb33-14"><a href="#cb33-14" aria-hidden="true" tabindex="-1"></a><span class="cf">with</span> <span class="bu">open</span>(<span class="st">'../models/glm_sev.pkl'</span>, <span class="st">'wb'</span>) <span class="im">as</span> f:</span>
<span id="cb33-15"><a href="#cb33-15" aria-hidden="true" tabindex="-1"></a>    pickle.dump(np.asarray(result.params), f)</span>
<span id="cb33-16"><a href="#cb33-16" aria-hidden="true" tabindex="-1"></a><span class="cf">with</span> <span class="bu">open</span>(<span class="st">'../models/glm_freq.pkl'</span>, <span class="st">'wb'</span>) <span class="im">as</span> f:</span>
<span id="cb33-17"><a href="#cb33-17" aria-hidden="true" tabindex="-1"></a>    pickle.dump(np.asarray(result_freq.params), f)</span>
<span id="cb33-18"><a href="#cb33-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-19"><a href="#cb33-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Feature order, so a future notebook can build a design matrix that matches</span></span>
<span id="cb33-20"><a href="#cb33-20" aria-hidden="true" tabindex="-1"></a><span class="cf">with</span> <span class="bu">open</span>(<span class="st">'../models/preprocessing.pkl'</span>, <span class="st">'wb'</span>) <span class="im">as</span> f:</span>
<span id="cb33-21"><a href="#cb33-21" aria-hidden="true" tabindex="-1"></a>    pickle.dump({<span class="st">'features'</span>: features, <span class="st">'cat_cols'</span>: [<span class="st">'Area'</span>, <span class="st">'VehBrand'</span>, <span class="st">'VehGas'</span>, <span class="st">'Region'</span>],</span>
<span id="cb33-22"><a href="#cb33-22" aria-hidden="true" tabindex="-1"></a>                 <span class="st">'columns'</span>: <span class="bu">list</span>(X_train.columns)}, f)</span>
<span id="cb33-23"><a href="#cb33-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-24"><a href="#cb33-24" aria-hidden="true" tabindex="-1"></a><span class="co"># ── Shared test-set definition (written once, here) ──────────────────────────</span></span>
<span id="cb33-25"><a href="#cb33-25" aria-hidden="true" tabindex="-1"></a>np.savez_compressed(</span>
<span id="cb33-26"><a href="#cb33-26" aria-hidden="true" tabindex="-1"></a>    <span class="st">'../results/test_split.npz'</span>,</span>
<span id="cb33-27"><a href="#cb33-27" aria-hidden="true" tabindex="-1"></a>    freq_idx_test        <span class="op">=</span> X_freq_test.index.values.astype(np.int64),</span>
<span id="cb33-28"><a href="#cb33-28" aria-hidden="true" tabindex="-1"></a>    freq_y_test          <span class="op">=</span> y_freq_test.values.astype(np.float32),</span>
<span id="cb33-29"><a href="#cb33-29" aria-hidden="true" tabindex="-1"></a>    freq_exposure_test   <span class="op">=</span> np.asarray(exp_test, dtype<span class="op">=</span>np.float32),</span>
<span id="cb33-30"><a href="#cb33-30" aria-hidden="true" tabindex="-1"></a>    freq_bonusmalus_test <span class="op">=</span> df_freq.loc[X_freq_test.index, <span class="st">'BonusMalus'</span>].values.astype(np.float32),</span>
<span id="cb33-31"><a href="#cb33-31" aria-hidden="true" tabindex="-1"></a>    freq_drivage_test    <span class="op">=</span> df_freq.loc[X_freq_test.index, <span class="st">'DrivAge'</span>].values.astype(np.float32),</span>
<span id="cb33-32"><a href="#cb33-32" aria-hidden="true" tabindex="-1"></a>    sev_idx_test         <span class="op">=</span> X_test.index.values.astype(np.int64),</span>
<span id="cb33-33"><a href="#cb33-33" aria-hidden="true" tabindex="-1"></a>    sev_y_test           <span class="op">=</span> y_test.values.astype(np.float32),</span>
<span id="cb33-34"><a href="#cb33-34" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb33-35"><a href="#cb33-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-36"><a href="#cb33-36" aria-hidden="true" tabindex="-1"></a><span class="co"># ── Predictions ──────────────────────────────────────────────────────────────</span></span>
<span id="cb33-37"><a href="#cb33-37" aria-hidden="true" tabindex="-1"></a>np.savez_compressed(</span>
<span id="cb33-38"><a href="#cb33-38" aria-hidden="true" tabindex="-1"></a>    <span class="st">'../results/predictions_glm.npz'</span>,</span>
<span id="cb33-39"><a href="#cb33-39" aria-hidden="true" tabindex="-1"></a>    sev_test_pred    <span class="op">=</span> np.asarray(y_pred, dtype<span class="op">=</span>np.float32),</span>
<span id="cb33-40"><a href="#cb33-40" aria-hidden="true" tabindex="-1"></a>    freq_test_rate   <span class="op">=</span> np.asarray(y_freq_pred <span class="op">/</span> exp_test, dtype<span class="op">=</span>np.float32),</span>
<span id="cb33-41"><a href="#cb33-41" aria-hidden="true" tabindex="-1"></a>    sev_on_freq_test <span class="op">=</span> np.asarray(sev_on_freq_test, dtype<span class="op">=</span>np.float32),</span>
<span id="cb33-42"><a href="#cb33-42" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb33-43"><a href="#cb33-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-44"><a href="#cb33-44" aria-hidden="true" tabindex="-1"></a><span class="co"># ── Metrics ──────────────────────────────────────────────────────────────────</span></span>
<span id="cb33-45"><a href="#cb33-45" aria-hidden="true" tabindex="-1"></a><span class="cf">with</span> <span class="bu">open</span>(<span class="st">'../results/metrics_glm.json'</span>, <span class="st">'w'</span>) <span class="im">as</span> f:</span>
<span id="cb33-46"><a href="#cb33-46" aria-hidden="true" tabindex="-1"></a>    json.dump({</span>
<span id="cb33-47"><a href="#cb33-47" aria-hidden="true" tabindex="-1"></a>        <span class="st">'model'</span>: <span class="st">'GLM'</span>,</span>
<span id="cb33-48"><a href="#cb33-48" aria-hidden="true" tabindex="-1"></a>        <span class="st">'severity'</span>:  {<span class="st">'MAE'</span>: <span class="bu">float</span>(mae),      <span class="st">'RMSE'</span>: <span class="bu">float</span>(rmse),      <span class="st">'GammaDeviance'</span>:   <span class="bu">float</span>(gd)},</span>
<span id="cb33-49"><a href="#cb33-49" aria-hidden="true" tabindex="-1"></a>        <span class="st">'frequency'</span>: {<span class="st">'MAE'</span>: <span class="bu">float</span>(mae_freq), <span class="st">'RMSE'</span>: <span class="bu">float</span>(rmse_freq), <span class="st">'PoissonDeviance'</span>: <span class="bu">float</span>(pd_score)},</span>
<span id="cb33-50"><a href="#cb33-50" aria-hidden="true" tabindex="-1"></a>    }, f, indent<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb33-51"><a href="#cb33-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-52"><a href="#cb33-52" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Saved GLM models, predictions and metrics.'</span>)</span>
<span id="cb33-53"><a href="#cb33-53" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'  test_split.npz       — </span><span class="sc">{</span><span class="bu">len</span>(X_freq_test)<span class="sc">:,}</span><span class="ss"> frequency rows, </span><span class="sc">{</span><span class="bu">len</span>(X_test)<span class="sc">:,}</span><span class="ss"> severity rows'</span>)</span>
<span id="cb33-54"><a href="#cb33-54" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'  predictions_glm.npz  — sev </span><span class="sc">{</span>y_pred<span class="sc">.</span>shape<span class="sc">}</span><span class="ss">, freq </span><span class="sc">{</span>y_freq_pred<span class="sc">.</span>shape<span class="sc">}</span><span class="ss">, sev_on_freq </span><span class="sc">{</span>sev_on_freq_test<span class="sc">.</span>shape<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb33-55"><a href="#cb33-55" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'  metrics_glm.json     — sev MAE </span><span class="sc">{</span>mae<span class="sc">:,.2f}</span><span class="ss"> | freq Poisson Deviance </span><span class="sc">{</span>pd_score<span class="sc">:,.2f}</span><span class="ss">'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Saved GLM models, predictions and metrics.
  test_split.npz       — 135,603 frequency rows, 5,288 severity rows
  predictions_glm.npz  — sev (5288,), freq (135603,), sev_on_freq (135603,)
  metrics_glm.json     — sev MAE 1,102.26 | freq Poisson Deviance 43,585.73</code></pre>
</div>
</div>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/dpark2380\.github\.io\/Insurance-Claims-Predictor\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>