<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-08-27">
<meta name="description" content="Head-to-head comparison of GLM, XGBoost, and neural network across frequency and severity. Combines both stages into a pure premium estimate.">

<title>Model Comparison &amp; Pure Premium – Insurance Claims Predictor</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-b85bc7c33db8c58e0ec93c3465666fed.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-3a0730cdd9a625ae55dc35d4063f4b4c.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed fullcontent quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Insurance Claims Predictor</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../notebooks.html"> 
<span class="menu-text">Notebooks</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/dpark2380/Insurance-Claims-Predictor"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Model Comparison &amp; Pure Premium</h1>
                  <div>
        <div class="description">
          Head-to-head comparison of GLM, XGBoost, and neural network across frequency and severity. Combines both stages into a pure premium estimate.
        </div>
      </div>
                </div>
  </div>
    
  
  <div class="quarto-title-meta">

      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">August 27, 2026</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<section id="notebook-5-model-comparison-pure-premium" class="level1">
<h1>Notebook 5: Model Comparison &amp; Pure Premium</h1>
<p>This notebook synthesises results from the three modelling notebooks into a single comparison and constructs a two-stage pure premium estimate.</p>
<p><strong>This notebook fits nothing.</strong> Every model was already fitted in notebooks 2–4, which save their fitted objects to <code>models/</code> and their test-set predictions and metrics to <code>results/</code>. Refitting them here would duplicate that work and — because each refit would be a <em>separate</em> fit — risk reporting numbers that differ from the notebooks they are supposed to be summarising. Everything below is loaded, not computed.</p>
<p><strong>Structure:</strong> - <strong>Part 1: Metric comparison</strong> — frequency and severity metrics side-by-side for GLM, XGBoost, and Neural Net - <strong>Part 2: Pure premium</strong> — frequency × severity per policy, compared across models - <strong>Part 3: Risk discrimination</strong> — lift charts and Gini coefficients across models - <strong>Part 4: Interpretability vs accuracy</strong> — regulatory considerations and model selection</p>
<p><strong>Prerequisite:</strong> notebooks 2, 3 and 4 must have been run, in that order. Notebook 2 writes the shared test-set definition that this notebook indexes everything against.</p>
<div id="imports" class="cell" data-execution_count="1">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> json</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> warnings</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>warnings.filterwarnings(<span class="st">'ignore'</span>)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="co"># No torch, no xgboost, no statsmodels, no sklearn — this notebook loads results,</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="co"># it does not produce them.</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>MODELS <span class="op">=</span> [<span class="st">'GLM'</span>, <span class="st">'XGBoost'</span>, <span class="st">'Neural Net'</span>]</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>KEYS   <span class="op">=</span> {<span class="st">'GLM'</span>: <span class="st">'glm'</span>, <span class="st">'XGBoost'</span>: <span class="st">'xgb'</span>, <span class="st">'Neural Net'</span>: <span class="st">'nn'</span>}</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>colors_map <span class="op">=</span> {<span class="st">'GLM'</span>: <span class="st">'#4C72B0'</span>, <span class="st">'XGBoost'</span>: <span class="st">'#DD8452'</span>, <span class="st">'Neural Net'</span>: <span class="st">'#55A868'</span>}</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>colors <span class="op">=</span> [colors_map[m] <span class="cf">for</span> m <span class="kw">in</span> MODELS]</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="co"># ── Shared test-set definition (written by notebook 2) ───────────────────────</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>split <span class="op">=</span> np.load(<span class="st">'../results/test_split.npz'</span>)</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>y_fr_te    <span class="op">=</span> split[<span class="st">'freq_y_test'</span>]           <span class="co"># actual ClaimNb</span></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>exp_te     <span class="op">=</span> split[<span class="st">'freq_exposure_test'</span>]    <span class="co"># actual Exposure</span></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>bm_te      <span class="op">=</span> split[<span class="st">'freq_bonusmalus_test'</span>]  <span class="co"># for the BonusMalus band charts</span></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>age_te     <span class="op">=</span> split[<span class="st">'freq_drivage_test'</span>]     <span class="co"># for the DrivAge band charts</span></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>y_sev_te   <span class="op">=</span> split[<span class="st">'sev_y_test'</span>]            <span class="co"># actual ClaimAmount</span></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a><span class="co"># ── Per-model predictions and metrics ────────────────────────────────────────</span></span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>preds   <span class="op">=</span> {m: np.load(<span class="ss">f'../results/predictions_</span><span class="sc">{</span>KEYS[m]<span class="sc">}</span><span class="ss">.npz'</span>) <span class="cf">for</span> m <span class="kw">in</span> MODELS}</span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>metrics <span class="op">=</span> {m: json.load(<span class="bu">open</span>(<span class="ss">f'../results/metrics_</span><span class="sc">{</span>KEYS[m]<span class="sc">}</span><span class="ss">.json'</span>)) <span class="cf">for</span> m <span class="kw">in</span> MODELS}</span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a><span class="co"># Every model must predict on exactly the same rows, or the comparison is meaningless</span></span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> m <span class="kw">in</span> MODELS:</span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a>    <span class="cf">assert</span> preds[m][<span class="st">'sev_test_pred'</span>].shape    <span class="op">==</span> y_sev_te.shape, <span class="ss">f'</span><span class="sc">{</span>m<span class="sc">}</span><span class="ss">: severity rows mismatch'</span></span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a>    <span class="cf">assert</span> preds[m][<span class="st">'freq_test_rate'</span>].shape   <span class="op">==</span> y_fr_te.shape,  <span class="ss">f'</span><span class="sc">{</span>m<span class="sc">}</span><span class="ss">: frequency rows mismatch'</span></span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a>    <span class="cf">assert</span> preds[m][<span class="st">'sev_on_freq_test'</span>].shape <span class="op">==</span> y_fr_te.shape,  <span class="ss">f'</span><span class="sc">{</span>m<span class="sc">}</span><span class="ss">: pure premium rows mismatch'</span></span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Loaded </span><span class="sc">{</span><span class="bu">len</span>(MODELS)<span class="sc">}</span><span class="ss"> models'</span>)</span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'  Frequency test set: </span><span class="sc">{</span>y_fr_te<span class="sc">.</span>shape[<span class="dv">0</span>]<span class="sc">:,}</span><span class="ss"> policies'</span>)</span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'  Severity  test set: </span><span class="sc">{</span>y_sev_te<span class="sc">.</span>shape[<span class="dv">0</span>]<span class="sc">:,}</span><span class="ss"> claims'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Loaded 3 models
  Frequency test set: 135,603 policies
  Severity  test set: 5,288 claims</code></pre>
</div>
</div>
<section id="part-1-metric-comparison" class="level2">
<h2 class="anchored" data-anchor-id="part-1-metric-comparison">Part 1: Metric Comparison</h2>
<p>Metrics recorded from each modelling notebook. These are test-set results; all models used the same 80/20 train-test split with <code>random_state=42</code>.</p>
<div id="metric-tables" class="cell" data-execution_count="2">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Metrics as recorded by each modelling notebook — loaded, not retyped.</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>sev_results <span class="op">=</span> pd.DataFrame(</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>    [{<span class="st">'Model'</span>: m, <span class="op">**</span>metrics[m][<span class="st">'severity'</span>]} <span class="cf">for</span> m <span class="kw">in</span> MODELS]</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>).set_index(<span class="st">'Model'</span>).rename(columns<span class="op">=</span>{<span class="st">'GammaDeviance'</span>: <span class="st">'Gamma Deviance'</span>})</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>freq_results <span class="op">=</span> pd.DataFrame(</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>    [{<span class="st">'Model'</span>: m, <span class="op">**</span>metrics[m][<span class="st">'frequency'</span>]} <span class="cf">for</span> m <span class="kw">in</span> MODELS]</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>).set_index(<span class="st">'Model'</span>).rename(columns<span class="op">=</span>{<span class="st">'PoissonDeviance'</span>: <span class="st">'Poisson Deviance'</span>})</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'=== Severity Metrics (</span><span class="sc">{</span>y_sev_te<span class="sc">.</span>shape[<span class="dv">0</span>]<span class="sc">:,}</span><span class="ss"> claims; target: ClaimAmount in EUR) ==='</span>)</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(sev_results.<span class="bu">round</span>({<span class="st">'MAE'</span>: <span class="dv">2</span>, <span class="st">'RMSE'</span>: <span class="dv">2</span>, <span class="st">'Gamma Deviance'</span>: <span class="dv">4</span>}).to_string())</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>()</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'=== Frequency Metrics (</span><span class="sc">{</span>y_fr_te<span class="sc">.</span>shape[<span class="dv">0</span>]<span class="sc">:,}</span><span class="ss"> test policies; target: ClaimNb) ==='</span>)</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(freq_results.<span class="bu">round</span>({<span class="st">'MAE'</span>: <span class="dv">4</span>, <span class="st">'RMSE'</span>: <span class="dv">4</span>, <span class="st">'Poisson Deviance'</span>: <span class="dv">2</span>}).to_string())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>=== Severity Metrics (5,288 claims; target: ClaimAmount in EUR) ===
                MAE     RMSE  Gamma Deviance
Model                                       
GLM         1102.26  2261.57          1.0595
XGBoost      938.56  2340.31          1.3611
Neural Net   957.42  2349.08          1.4114

=== Frequency Metrics (135,603 test policies; target: ClaimNb) ===
               MAE    RMSE  Poisson Deviance
Model                                       
GLM         0.0988  0.2370          43585.73
XGBoost     0.0966  0.2352          41478.64
Neural Net  0.0972  0.2371          42250.46</code></pre>
</div>
</div>
<div id="metric-charts" class="cell" data-execution_count="3">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">2</span>, <span class="dv">3</span>, figsize<span class="op">=</span>(<span class="dv">16</span>, <span class="dv">9</span>))</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>colors <span class="op">=</span> [<span class="st">'#4C72B0'</span>, <span class="st">'#DD8452'</span>, <span class="st">'#55A868'</span>]</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Severity row</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> ax, metric <span class="kw">in</span> <span class="bu">zip</span>(axes[<span class="dv">0</span>], [<span class="st">'MAE'</span>, <span class="st">'RMSE'</span>, <span class="st">'Gamma Deviance'</span>]):</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>    bars <span class="op">=</span> ax.bar(sev_results.index, sev_results[metric], color<span class="op">=</span>colors, edgecolor<span class="op">=</span><span class="st">'white'</span>)</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>    ax.set_title(<span class="ss">f'Severity — </span><span class="sc">{</span>metric<span class="sc">}</span><span class="ss">'</span>, fontsize<span class="op">=</span><span class="dv">11</span>)</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>    ax.set_ylabel(metric)</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>    ax.tick_params(axis<span class="op">=</span><span class="st">'x'</span>, rotation<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> bar <span class="kw">in</span> bars:</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>        ax.text(</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>            bar.get_x() <span class="op">+</span> bar.get_width() <span class="op">/</span> <span class="dv">2</span>,</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>            bar.get_height() <span class="op">*</span> <span class="fl">1.01</span>,</span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>            <span class="ss">f'</span><span class="sc">{</span>bar<span class="sc">.</span>get_height()<span class="sc">:,.2f}</span><span class="ss">'</span>,</span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>            ha<span class="op">=</span><span class="st">'center'</span>, va<span class="op">=</span><span class="st">'bottom'</span>, fontsize<span class="op">=</span><span class="dv">9</span></span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>        )</span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Frequency row</span></span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> ax, metric <span class="kw">in</span> <span class="bu">zip</span>(axes[<span class="dv">1</span>], [<span class="st">'MAE'</span>, <span class="st">'RMSE'</span>, <span class="st">'Poisson Deviance'</span>]):</span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a>    bars <span class="op">=</span> ax.bar(freq_results.index, freq_results[metric], color<span class="op">=</span>colors, edgecolor<span class="op">=</span><span class="st">'white'</span>)</span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a>    ax.set_title(<span class="ss">f'Frequency — </span><span class="sc">{</span>metric<span class="sc">}</span><span class="ss">'</span>, fontsize<span class="op">=</span><span class="dv">11</span>)</span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a>    ax.set_ylabel(metric)</span>
<span id="cb5-23"><a href="#cb5-23" aria-hidden="true" tabindex="-1"></a>    ax.tick_params(axis<span class="op">=</span><span class="st">'x'</span>, rotation<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb5-24"><a href="#cb5-24" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> bar <span class="kw">in</span> bars:</span>
<span id="cb5-25"><a href="#cb5-25" aria-hidden="true" tabindex="-1"></a>        ax.text(</span>
<span id="cb5-26"><a href="#cb5-26" aria-hidden="true" tabindex="-1"></a>            bar.get_x() <span class="op">+</span> bar.get_width() <span class="op">/</span> <span class="dv">2</span>,</span>
<span id="cb5-27"><a href="#cb5-27" aria-hidden="true" tabindex="-1"></a>            bar.get_height() <span class="op">*</span> <span class="fl">1.01</span>,</span>
<span id="cb5-28"><a href="#cb5-28" aria-hidden="true" tabindex="-1"></a>            <span class="ss">f'</span><span class="sc">{</span>bar<span class="sc">.</span>get_height()<span class="sc">:,.4g}</span><span class="ss">'</span>,</span>
<span id="cb5-29"><a href="#cb5-29" aria-hidden="true" tabindex="-1"></a>            ha<span class="op">=</span><span class="st">'center'</span>, va<span class="op">=</span><span class="st">'bottom'</span>, fontsize<span class="op">=</span><span class="dv">9</span></span>
<span id="cb5-30"><a href="#cb5-30" aria-hidden="true" tabindex="-1"></a>        )</span>
<span id="cb5-31"><a href="#cb5-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-32"><a href="#cb5-32" aria-hidden="true" tabindex="-1"></a>plt.suptitle(<span class="st">'Model Comparison: Severity and Frequency'</span>, fontsize<span class="op">=</span><span class="dv">14</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb5-33"><a href="#cb5-33" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb5-34"><a href="#cb5-34" aria-hidden="true" tabindex="-1"></a>plt.savefig(<span class="st">'../results/18_metric_comparison.png'</span>, dpi<span class="op">=</span><span class="dv">150</span>, bbox_inches<span class="op">=</span><span class="st">'tight'</span>)</span>
<span id="cb5-35"><a href="#cb5-35" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="05_comparison_files/figure-html/cell-4-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<section id="reading-the-metric-table" class="level3">
<h3 class="anchored" data-anchor-id="reading-the-metric-table">Reading the metric table</h3>
<p><strong>Frequency:</strong> XGBoost has the lowest Poisson deviance (41,479 vs the GLM’s 43,586, a 4.8% reduction) and the lowest MAE and RMSE too — a clean, consistent win across every metric. The Neural Net sits between the two on all three. This is a genuine improvement, not an artifact of the earlier un-offset GLM fit — these numbers come from the offset-corrected model.</p>
<p><strong>Severity looks contradictory at first glance, and isn’t.</strong> XGBoost (938 EUR) and the Neural Net (957 EUR) beat the GLM (1,102 EUR) on MAE, yet both are <em>worse</em> than the GLM on Gamma Deviance — and worse than an intercept-only baseline (deviance ≈ 1.064; see notebook 02, Appendix B). MAE and Gamma Deviance are answering different questions. MAE rewards being close on the common, small claims; Gamma Deviance weights errors relative to the predicted mean, so a systematic miss on a handful of very large claims costs far more under deviance than under MAE. That is exactly what’s happening here: XGBoost’s test predictions span roughly 310–1,500 EUR against actual claims running up to 16,451 EUR, while the GLM’s span 873–2,506 EUR. XGBoost looks more accurate on ordinary claims because it collapses harder toward the centre of the distribution — and that same collapse is what makes it worse at the one job severity models actually need to do, which is not underprice the claims that drive total portfolio cost.</p>
<p>This isn’t specific to this run’s hyperparameters in a way that rescues XGBoost elsewhere: notebook 02’s Appendix B found a <em>carefully tuned</em> gradient booster only matched the GLM under cross-validation (p = 0.14, not significant), and the untuned model used here does worse than doing nothing. The severity ceiling is a data property, not a model-choice problem — see Appendix B for the full argument.</p>
<p>This divergence — better MAE, worse deviance — is what drives the pure premium gap in Part 2.</p>
</section>
</section>
<section id="part-2-pure-premium" class="level2">
<h2 class="anchored" data-anchor-id="part-2-pure-premium">Part 2: Pure Premium</h2>
<p>Pure premium is the expected annual claim cost of a policy — what the policy costs the insurer before expenses, profit margin or capital loading. It is the product of the two stages:</p>
<p><span class="math display">\[\text{Pure Premium} = \hat{p}_{\text{freq}} \times \hat{\mu}_{\text{sev}}\]</span></p>
<p>where <span class="math inline">\(\hat{p}_{\text{freq}}\)</span> is the expected number of claims per year and <span class="math inline">\(\hat{\mu}_{\text{sev}}\)</span> is the expected cost of a claim given one occurs.</p>
<p><strong>Why the two stages are modelled separately.</strong> Frequency and severity are driven by different things. Whether you crash is about driving behaviour and exposure to traffic — BonusMalus, driver age, population density. What the crash costs is about the vehicle and the repair market — vehicle value, power, regional labour rates. Modelling the product directly (a Tweedie GLM) is possible, but fitting the two halves separately lets each use the distribution that actually fits it (Poisson for counts, Gamma for costs) and makes the resulting rating factors far easier to explain to a regulator.</p>
<p><strong>Row alignment is the thing to get right here.</strong> Multiplying frequency by severity is only meaningful when both refer to <em>the same policy</em>. The frequency test set is a shuffled 20% sample, so the severity model has to be scored on those same shuffled rows — which is exactly what <code>sev_on_freq_test</code> is, computed inside each modelling notebook where the rows are unambiguous. Taking a positional slice of the full dataset instead would pair each policy’s frequency with a different policy’s severity, and every downstream number would be quietly wrong.</p>
<div id="f2c92bad" class="cell" data-execution_count="4">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Pure premium per policy, per model — both halves scored on the same test rows.</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>pp_models <span class="op">=</span> {</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>    m: preds[m][<span class="st">'freq_test_rate'</span>] <span class="op">*</span> preds[m][<span class="st">'sev_on_freq_test'</span>]</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> m <span class="kw">in</span> MODELS</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Empirical benchmark: what the test portfolio actually cost per policy-year.</span></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Total claim cost is not observable per policy here, so approximate it as</span></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a><span class="co"># (observed claim rate) x (mean claim size) across the severity test set.</span></span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>emp_rate <span class="op">=</span> y_fr_te.<span class="bu">sum</span>() <span class="op">/</span> exp_te.<span class="bu">sum</span>()</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>emp_sev  <span class="op">=</span> y_sev_te.mean()</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>emp_pp   <span class="op">=</span> emp_rate <span class="op">*</span> emp_sev</span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Empirical benchmark: </span><span class="sc">{</span>emp_rate<span class="sc">:.4f}</span><span class="ss"> claims/year x </span><span class="sc">{</span>emp_sev<span class="sc">:,.0f}</span><span class="ss"> EUR = </span><span class="sc">{</span>emp_pp<span class="sc">:,.2f}</span><span class="ss"> EUR</span><span class="ch">\n</span><span class="ss">'</span>)</span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> m <span class="kw">in</span> MODELS:</span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f'</span><span class="sc">{</span>m<span class="sc">:12}</span><span class="ss"> mean pure premium: </span><span class="sc">{</span>pp_models[m]<span class="sc">.</span>mean()<span class="sc">:8,.2f}</span><span class="ss"> EUR '</span></span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a>          <span class="ss">f'(median </span><span class="sc">{</span>np<span class="sc">.</span>median(pp_models[m])<span class="sc">:7,.2f}</span><span class="ss">)'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Empirical benchmark: 0.1011 claims/year x 1,558 EUR = 157.52 EUR

GLM          mean pure premium:   173.75 EUR (median  147.83)
XGBoost      mean pure premium:   112.46 EUR (median   75.34)
Neural Net   mean pure premium:   107.18 EUR (median   77.58)</code></pre>
</div>
</div>
<section id="pure-premium-comparison" class="level3">
<h3 class="anchored" data-anchor-id="pure-premium-comparison">2.4 Pure Premium Comparison</h3>
<div id="pp-charts" class="cell" data-execution_count="5">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">15</span>, <span class="dv">5</span>))</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Distribution of pure premiums</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>cap <span class="op">=</span> np.percentile(np.concatenate(<span class="bu">list</span>(pp_models.values())), <span class="dv">99</span>)</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> name, pp <span class="kw">in</span> pp_models.items():</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>    axes[<span class="dv">0</span>].hist(</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>        np.clip(pp, <span class="dv">0</span>, cap), bins<span class="op">=</span><span class="dv">80</span>, alpha<span class="op">=</span><span class="fl">0.6</span>,</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>        label<span class="op">=</span><span class="ss">f'</span><span class="sc">{</span>name<span class="sc">}</span><span class="ss"> (mean=</span><span class="sc">{</span>pp<span class="sc">.</span>mean()<span class="sc">:.0f}</span><span class="ss">)'</span>, color<span class="op">=</span>colors_map[name], edgecolor<span class="op">=</span><span class="st">'none'</span></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].axvline(emp_pp, color<span class="op">=</span><span class="st">'black'</span>, linestyle<span class="op">=</span><span class="st">'--'</span>, linewidth<span class="op">=</span><span class="dv">1</span>,</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>                label<span class="op">=</span><span class="ss">f'Empirical (</span><span class="sc">{</span>emp_pp<span class="sc">:.0f}</span><span class="ss">)'</span>)</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_xlabel(<span class="st">'Pure Premium (EUR, capped at 99th pct)'</span>)</span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_ylabel(<span class="st">'Policies'</span>)</span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_title(<span class="st">'Distribution of Pure Premiums by Model'</span>)</span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].legend()</span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Mean by BonusMalus band — bm_te is aligned to the same test rows as pp</span></span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a>bm_labels <span class="op">=</span> [<span class="st">'50-60'</span>, <span class="st">'61-80'</span>, <span class="st">'81-100'</span>, <span class="st">'101-150'</span>, <span class="st">'150+'</span>]</span>
<span id="cb8-19"><a href="#cb8-19" aria-hidden="true" tabindex="-1"></a>bm_bins <span class="op">=</span> pd.cut(bm_te, bins<span class="op">=</span>[<span class="dv">49</span>, <span class="dv">60</span>, <span class="dv">80</span>, <span class="dv">100</span>, <span class="dv">150</span>, <span class="dv">230</span>], labels<span class="op">=</span>bm_labels)</span>
<span id="cb8-20"><a href="#cb8-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-21"><a href="#cb8-21" aria-hidden="true" tabindex="-1"></a>x <span class="op">=</span> <span class="bu">range</span>(<span class="bu">len</span>(bm_labels))</span>
<span id="cb8-22"><a href="#cb8-22" aria-hidden="true" tabindex="-1"></a>width <span class="op">=</span> <span class="fl">0.25</span></span>
<span id="cb8-23"><a href="#cb8-23" aria-hidden="true" tabindex="-1"></a>bm_table <span class="op">=</span> {}</span>
<span id="cb8-24"><a href="#cb8-24" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i, (name, pp) <span class="kw">in</span> <span class="bu">enumerate</span>(pp_models.items()):</span>
<span id="cb8-25"><a href="#cb8-25" aria-hidden="true" tabindex="-1"></a>    band_mean <span class="op">=</span> pd.Series(pp).groupby(bm_bins, observed<span class="op">=</span><span class="va">False</span>).mean()</span>
<span id="cb8-26"><a href="#cb8-26" aria-hidden="true" tabindex="-1"></a>    bm_table[name] <span class="op">=</span> band_mean</span>
<span id="cb8-27"><a href="#cb8-27" aria-hidden="true" tabindex="-1"></a>    axes[<span class="dv">1</span>].bar([j <span class="op">+</span> i <span class="op">*</span> width <span class="cf">for</span> j <span class="kw">in</span> x], band_mean, width<span class="op">=</span>width,</span>
<span id="cb8-28"><a href="#cb8-28" aria-hidden="true" tabindex="-1"></a>                label<span class="op">=</span>name, color<span class="op">=</span>colors_map[name], edgecolor<span class="op">=</span><span class="st">'white'</span>)</span>
<span id="cb8-29"><a href="#cb8-29" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_xticks([j <span class="op">+</span> width <span class="cf">for</span> j <span class="kw">in</span> x])</span>
<span id="cb8-30"><a href="#cb8-30" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_xticklabels(bm_labels)</span>
<span id="cb8-31"><a href="#cb8-31" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_xlabel(<span class="st">'BonusMalus Band'</span>)</span>
<span id="cb8-32"><a href="#cb8-32" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_ylabel(<span class="st">'Mean Pure Premium (EUR)'</span>)</span>
<span id="cb8-33"><a href="#cb8-33" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_title(<span class="st">'Mean Pure Premium by BonusMalus Band'</span>)</span>
<span id="cb8-34"><a href="#cb8-34" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].legend()</span>
<span id="cb8-35"><a href="#cb8-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-36"><a href="#cb8-36" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb8-37"><a href="#cb8-37" aria-hidden="true" tabindex="-1"></a>plt.savefig(<span class="st">'../results/19_pure_premium_comparison.png'</span>, dpi<span class="op">=</span><span class="dv">150</span>, bbox_inches<span class="op">=</span><span class="st">'tight'</span>)</span>
<span id="cb8-38"><a href="#cb8-38" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb8-39"><a href="#cb8-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-40"><a href="#cb8-40" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Mean pure premium by BonusMalus band (EUR):'</span>)</span>
<span id="cb8-41"><a href="#cb8-41" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(pd.DataFrame(bm_table).<span class="bu">round</span>(<span class="dv">0</span>).to_string())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="05_comparison_files/figure-html/cell-6-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Mean pure premium by BonusMalus band (EUR):
            GLM  XGBoost  Neural Net
50-60     136.0     89.0        89.0
61-80     203.0    135.0       117.0
81-100    325.0    201.0       182.0
101-150   620.0    407.0       361.0
150+     2132.0    543.0       871.0</code></pre>
</div>
</div>
<div id="pp-by-age" class="cell" data-execution_count="6">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Mean pure premium by driver age band — age_te is aligned to the same test rows</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>age_labels <span class="op">=</span> [<span class="st">'18-25'</span>, <span class="st">'26-35'</span>, <span class="st">'36-45'</span>, <span class="st">'46-55'</span>, <span class="st">'56-65'</span>, <span class="st">'65+'</span>]</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>age_bins <span class="op">=</span> pd.cut(age_te, bins<span class="op">=</span>[<span class="dv">17</span>, <span class="dv">25</span>, <span class="dv">35</span>, <span class="dv">45</span>, <span class="dv">55</span>, <span class="dv">65</span>, <span class="dv">100</span>], labels<span class="op">=</span>age_labels)</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">12</span>, <span class="dv">5</span>))</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>width <span class="op">=</span> <span class="fl">0.25</span></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>x <span class="op">=</span> <span class="bu">range</span>(<span class="bu">len</span>(age_labels))</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>age_table <span class="op">=</span> {}</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i, (name, pp) <span class="kw">in</span> <span class="bu">enumerate</span>(pp_models.items()):</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>    band_mean <span class="op">=</span> pd.Series(pp).groupby(age_bins, observed<span class="op">=</span><span class="va">False</span>).mean()</span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>    age_table[name] <span class="op">=</span> band_mean</span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>    ax.bar([j <span class="op">+</span> i <span class="op">*</span> width <span class="cf">for</span> j <span class="kw">in</span> x], band_mean, width<span class="op">=</span>width,</span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>           label<span class="op">=</span>name, color<span class="op">=</span>colors_map[name], edgecolor<span class="op">=</span><span class="st">'white'</span>)</span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a>ax.set_xticks([j <span class="op">+</span> width <span class="cf">for</span> j <span class="kw">in</span> x])</span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a>ax.set_xticklabels(age_labels)</span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">'Driver Age Band'</span>)</span>
<span id="cb10-18"><a href="#cb10-18" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">'Mean Pure Premium (EUR)'</span>)</span>
<span id="cb10-19"><a href="#cb10-19" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">'Mean Pure Premium by Driver Age Band'</span>)</span>
<span id="cb10-20"><a href="#cb10-20" aria-hidden="true" tabindex="-1"></a>ax.legend()</span>
<span id="cb10-21"><a href="#cb10-21" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb10-22"><a href="#cb10-22" aria-hidden="true" tabindex="-1"></a>plt.savefig(<span class="st">'../results/20_pure_premium_by_age.png'</span>, dpi<span class="op">=</span><span class="dv">150</span>, bbox_inches<span class="op">=</span><span class="st">'tight'</span>)</span>
<span id="cb10-23"><a href="#cb10-23" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb10-24"><a href="#cb10-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-25"><a href="#cb10-25" aria-hidden="true" tabindex="-1"></a>age_df <span class="op">=</span> pd.DataFrame(age_table)</span>
<span id="cb10-26"><a href="#cb10-26" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Mean pure premium by driver age band (EUR):'</span>)</span>
<span id="cb10-27"><a href="#cb10-27" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(age_df.<span class="bu">round</span>(<span class="dv">0</span>).to_string())</span>
<span id="cb10-28"><a href="#cb10-28" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'</span><span class="ch">\n</span><span class="st">Young-driver loading (18-25 relative to 36-45):'</span>)</span>
<span id="cb10-29"><a href="#cb10-29" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> name <span class="kw">in</span> MODELS:</span>
<span id="cb10-30"><a href="#cb10-30" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f'  </span><span class="sc">{</span>name<span class="sc">:12}</span><span class="ss"> </span><span class="sc">{</span>age_df<span class="sc">.</span>loc[<span class="st">"18-25"</span>, name] <span class="op">/</span> age_df<span class="sc">.</span>loc[<span class="st">"36-45"</span>, name]<span class="sc">:.2f}</span><span class="ss">x'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="05_comparison_files/figure-html/cell-7-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Mean pure premium by driver age band (EUR):
         GLM  XGBoost  Neural Net
18-25  275.0    198.0       167.0
26-35  192.0    103.0       110.0
36-45  155.0    104.0        99.0
46-55  154.0    113.0       100.0
56-65  168.0    104.0       106.0
65+    177.0    115.0       108.0

Young-driver loading (18-25 relative to 36-45):
  GLM          1.78x
  XGBoost      1.90x
  Neural Net   1.70x</code></pre>
</div>
</div>
</section>
<section id="reading-the-pure-premium-comparison" class="level3">
<h3 class="anchored" data-anchor-id="reading-the-pure-premium-comparison">Reading the pure premium comparison</h3>
<p>The empirical benchmark (157.52 EUR/policy-year) is the observed claim rate times the mean observed severity across the test set — a naive, model-free reference point. Against it: the GLM overshoots by about 10% (173.75 EUR), while XGBoost and the Neural Net undershoot by about 29% and 32% respectively (112.46 EUR, 107.18 EUR).</p>
<p>That asymmetry is the severity collapse from Part 1 propagating through the multiplication. All three models see the same claim frequency signal; what differs is severity, and XGBoost/NN’s tighter, lower predictions drag the whole portfolio estimate down. Read literally, deploying either ML model’s severity stage as-is would systematically <strong>underprice</strong> the book — a more consequential failure mode for an insurer than a modest overshoot.</p>
<p><strong>A caveat that applies to every number in this section, including the empirical benchmark.</strong> Pure premium here is <code>freq_test_rate × sev_on_freq_test</code>: frequency counts every claim event (<code>ClaimNb</code>, ~36,056 across the full dataset), while severity is fit only on the ~26,439 claims that have a matching cost record. About 26.8% of claim events have no price attached, concentrated in specific segments (<code>VehBrand</code> and <code>VehGas</code> in particular — see the frequency/severity join-gap finding). That inflates every pure premium figure in this section by a similar amount, since the mechanism is identical for the empirical benchmark and all three models. It does <strong>not</strong> change which model wins or the Gini/lift comparisons in Part 3, which depend only on relative ranking — but none of the EUR figures here should be read as a calibrated rate card without correcting for it (e.g.&nbsp;a <code>P(priced | claim)</code> stage multiplied in).</p>
<p><strong>BonusMalus and age bands.</strong> The young-driver loading is directionally consistent across all three models (1.70–1.90x for 18–25 vs 36–45) — reassuring, since the qualitative pricing story doesn’t depend on model choice even though its exact size does. The BonusMalus 150+ band is the exception worth flagging: the GLM’s premium there (2,132 EUR) is roughly 4x XGBoost’s (543 EUR) and 2.4x the Neural Net’s (871 EUR), a far larger gap than at any other band. The GLM’s log link extrapolates multiplicatively without bound for extreme covariate values; the tree-based and neural models are bounded by what they saw in training and can’t extrapolate past it. That makes the GLM the most responsive to BonusMalus at the top of the scale, but also the most exposed to a small number of high-leverage records driving that band’s estimate.</p>
</section>
</section>
<section id="part-3-risk-discrimination" class="level2">
<h2 class="anchored" data-anchor-id="part-3-risk-discrimination">Part 3: Risk Discrimination</h2>
<p>The Gini coefficient (or normalised Gini) measures how well a model rank-orders policies by risk. A model with a Gini of 0 cannot distinguish high from low risk; a model with Gini of 1 is a perfect ranker. This is more relevant for pricing than MAE or RMSE.</p>
<div id="gini" class="cell" data-execution_count="7">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> gini(actual, predicted):</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Normalised Gini coefficient — 1 is perfect ranking, 0 is random.</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="co">    Ranks policies by predicted risk, then measures how much of the actual claim</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="co">    volume is concentrated in the top-ranked policies. Normalising by the score a</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a><span class="co">    perfect ranker would achieve makes the result comparable across datasets.</span></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a><span class="co">    """</span></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>    df <span class="op">=</span> pd.DataFrame({<span class="st">'actual'</span>: actual, <span class="st">'predicted'</span>: predicted})</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>    df_sorted <span class="op">=</span> df.sort_values(<span class="st">'predicted'</span>, ascending<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>    cum_actual <span class="op">=</span> df_sorted[<span class="st">'actual'</span>].cumsum() <span class="op">/</span> df_sorted[<span class="st">'actual'</span>].<span class="bu">sum</span>()</span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>    gini_model <span class="op">=</span> <span class="dv">1</span> <span class="op">-</span> <span class="dv">2</span> <span class="op">*</span> cum_actual.mean()</span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a>    df_perfect <span class="op">=</span> df.sort_values(<span class="st">'actual'</span>, ascending<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a>    cum_perfect <span class="op">=</span> df_perfect[<span class="st">'actual'</span>].cumsum() <span class="op">/</span> df_perfect[<span class="st">'actual'</span>].<span class="bu">sum</span>()</span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a>    gini_perfect <span class="op">=</span> <span class="dv">1</span> <span class="op">-</span> <span class="dv">2</span> <span class="op">*</span> cum_perfect.mean()</span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> gini_model <span class="op">/</span> gini_perfect</span>
<span id="cb12-16"><a href="#cb12-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-17"><a href="#cb12-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Frequency Gini ranks by expected claim COUNT (rate x exposure), since the actual</span></span>
<span id="cb12-18"><a href="#cb12-18" aria-hidden="true" tabindex="-1"></a><span class="co"># being ranked is a count. Pure premium Gini ranks by expected cost.</span></span>
<span id="cb12-19"><a href="#cb12-19" aria-hidden="true" tabindex="-1"></a>gini_results <span class="op">=</span> pd.DataFrame([</span>
<span id="cb12-20"><a href="#cb12-20" aria-hidden="true" tabindex="-1"></a>    {</span>
<span id="cb12-21"><a href="#cb12-21" aria-hidden="true" tabindex="-1"></a>        <span class="st">'Model'</span>: m,</span>
<span id="cb12-22"><a href="#cb12-22" aria-hidden="true" tabindex="-1"></a>        <span class="st">'Frequency Gini'</span>:    gini(y_fr_te, preds[m][<span class="st">'freq_test_rate'</span>] <span class="op">*</span> exp_te),</span>
<span id="cb12-23"><a href="#cb12-23" aria-hidden="true" tabindex="-1"></a>        <span class="st">'Pure Premium Gini'</span>: gini(y_fr_te, pp_models[m]),</span>
<span id="cb12-24"><a href="#cb12-24" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb12-25"><a href="#cb12-25" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> m <span class="kw">in</span> MODELS</span>
<span id="cb12-26"><a href="#cb12-26" aria-hidden="true" tabindex="-1"></a>]).set_index(<span class="st">'Model'</span>)</span>
<span id="cb12-27"><a href="#cb12-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-28"><a href="#cb12-28" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(gini_results.<span class="bu">round</span>(<span class="dv">4</span>).to_string())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Frequency Gini  Pure Premium Gini
Model                                        
GLM                 0.2660             0.1365
XGBoost             0.3565             0.2433
Neural Net          0.3254             0.1853</code></pre>
</div>
</div>
<div id="lorenz-curves" class="cell" data-execution_count="8">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> lorenz(actual, predicted):</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Returns (x, y) Lorenz curve coordinates."""</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>    df <span class="op">=</span> pd.DataFrame({<span class="st">'actual'</span>: actual, <span class="st">'predicted'</span>: predicted})</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>    df <span class="op">=</span> df.sort_values(<span class="st">'predicted'</span>, ascending<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>    x <span class="op">=</span> np.linspace(<span class="dv">0</span>, <span class="dv">1</span>, <span class="bu">len</span>(df))</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>    y <span class="op">=</span> df[<span class="st">'actual'</span>].cumsum() <span class="op">/</span> df[<span class="st">'actual'</span>].<span class="bu">sum</span>()</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> x, y.values</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">8</span>, <span class="dv">7</span>))</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>ax.plot([<span class="dv">0</span>, <span class="dv">1</span>], [<span class="dv">0</span>, <span class="dv">1</span>], <span class="st">'k--'</span>, label<span class="op">=</span><span class="st">'Random'</span>, linewidth<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> name <span class="kw">in</span> MODELS:</span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>    freq_pred <span class="op">=</span> preds[name][<span class="st">'freq_test_rate'</span>] <span class="op">*</span> exp_te</span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a>    g <span class="op">=</span> gini_results.loc[name, <span class="st">'Frequency Gini'</span>]</span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a>    x, y <span class="op">=</span> lorenz(y_fr_te, freq_pred)</span>
<span id="cb14-16"><a href="#cb14-16" aria-hidden="true" tabindex="-1"></a>    ax.plot(x, y, label<span class="op">=</span><span class="ss">f'</span><span class="sc">{</span>name<span class="sc">}</span><span class="ss"> (Gini=</span><span class="sc">{</span>g<span class="sc">:.3f}</span><span class="ss">)'</span>, color<span class="op">=</span>colors_map[name])</span>
<span id="cb14-17"><a href="#cb14-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-18"><a href="#cb14-18" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">'Proportion of Policies (ranked by predicted risk, low to high)'</span>)</span>
<span id="cb14-19"><a href="#cb14-19" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">'Proportion of Claims'</span>)</span>
<span id="cb14-20"><a href="#cb14-20" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">'Lorenz Curves — Frequency Model Risk Discrimination'</span>)</span>
<span id="cb14-21"><a href="#cb14-21" aria-hidden="true" tabindex="-1"></a>ax.legend()</span>
<span id="cb14-22"><a href="#cb14-22" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb14-23"><a href="#cb14-23" aria-hidden="true" tabindex="-1"></a>plt.savefig(<span class="st">'../results/21_lorenz_curves.png'</span>, dpi<span class="op">=</span><span class="dv">150</span>, bbox_inches<span class="op">=</span><span class="st">'tight'</span>)</span>
<span id="cb14-24"><a href="#cb14-24" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="05_comparison_files/figure-html/cell-9-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<div id="decile-lift" class="cell" data-execution_count="9">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Decile lift chart comparing all three frequency models.</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="co"># duplicates='drop' matters here: the neural net clips negative rates to zero, so</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="co"># many predictions are tied and some decile boundaries land on the same value.</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Without it qcut raises, or (worse) produces wildly unequal groups that distort</span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a><span class="co"># the gradient. A model with ties may therefore end up with fewer than 10 groups.</span></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">12</span>, <span class="dv">5</span>))</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>width <span class="op">=</span> <span class="fl">0.25</span></span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>lift_table <span class="op">=</span> {}</span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i, name <span class="kw">in</span> <span class="bu">enumerate</span>(MODELS):</span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>    df_lift <span class="op">=</span> pd.DataFrame({<span class="st">'actual'</span>: y_fr_te, <span class="st">'predicted'</span>: preds[name][<span class="st">'freq_test_rate'</span>]})</span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a>    df_lift[<span class="st">'decile'</span>] <span class="op">=</span> pd.qcut(df_lift[<span class="st">'predicted'</span>], q<span class="op">=</span><span class="dv">10</span>, labels<span class="op">=</span><span class="va">False</span>, duplicates<span class="op">=</span><span class="st">'drop'</span>) <span class="op">+</span> <span class="dv">1</span></span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a>    lift <span class="op">=</span> df_lift.groupby(<span class="st">'decile'</span>)[<span class="st">'actual'</span>].mean()</span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a>    lift_table[name] <span class="op">=</span> lift</span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a>    ax.bar(lift.index <span class="op">+</span> i <span class="op">*</span> width <span class="op">-</span> width, lift.values, width<span class="op">=</span>width,</span>
<span id="cb15-17"><a href="#cb15-17" aria-hidden="true" tabindex="-1"></a>           label<span class="op">=</span>name, color<span class="op">=</span>colors_map[name], edgecolor<span class="op">=</span><span class="st">'white'</span>)</span>
<span id="cb15-18"><a href="#cb15-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-19"><a href="#cb15-19" aria-hidden="true" tabindex="-1"></a>ax.set_xticks(np.arange(<span class="dv">1</span>, <span class="bu">max</span>(<span class="bu">len</span>(v) <span class="cf">for</span> v <span class="kw">in</span> lift_table.values()) <span class="op">+</span> <span class="dv">1</span>))</span>
<span id="cb15-20"><a href="#cb15-20" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">'Decile (1 = lowest predicted risk, highest = riskiest)'</span>)</span>
<span id="cb15-21"><a href="#cb15-21" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">'Mean Actual Claim Count'</span>)</span>
<span id="cb15-22"><a href="#cb15-22" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">'Decile Lift Chart — Frequency Models'</span>)</span>
<span id="cb15-23"><a href="#cb15-23" aria-hidden="true" tabindex="-1"></a>ax.legend()</span>
<span id="cb15-24"><a href="#cb15-24" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb15-25"><a href="#cb15-25" aria-hidden="true" tabindex="-1"></a>plt.savefig(<span class="st">'../results/22_decile_lift_comparison.png'</span>, dpi<span class="op">=</span><span class="dv">150</span>, bbox_inches<span class="op">=</span><span class="st">'tight'</span>)</span>
<span id="cb15-26"><a href="#cb15-26" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb15-27"><a href="#cb15-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-28"><a href="#cb15-28" aria-hidden="true" tabindex="-1"></a>lift_df <span class="op">=</span> pd.DataFrame(lift_table)</span>
<span id="cb15-29"><a href="#cb15-29" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Mean actual claim count by predicted-risk decile:'</span>)</span>
<span id="cb15-30"><a href="#cb15-30" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(lift_df.<span class="bu">round</span>(<span class="dv">4</span>).to_string())</span>
<span id="cb15-31"><a href="#cb15-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-32"><a href="#cb15-32" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'</span><span class="ch">\n</span><span class="st">Top-to-bottom lift (riskiest group / safest group):'</span>)</span>
<span id="cb15-33"><a href="#cb15-33" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> name <span class="kw">in</span> MODELS:</span>
<span id="cb15-34"><a href="#cb15-34" aria-hidden="true" tabindex="-1"></a>    s <span class="op">=</span> lift_table[name].dropna()</span>
<span id="cb15-35"><a href="#cb15-35" aria-hidden="true" tabindex="-1"></a>    n_groups <span class="op">=</span> <span class="bu">len</span>(s)</span>
<span id="cb15-36"><a href="#cb15-36" aria-hidden="true" tabindex="-1"></a>    note <span class="op">=</span> <span class="st">''</span> <span class="cf">if</span> n_groups <span class="op">==</span> <span class="dv">10</span> <span class="cf">else</span> <span class="ss">f'  [</span><span class="sc">{</span>n_groups<span class="sc">}</span><span class="ss"> groups — tied predictions]'</span></span>
<span id="cb15-37"><a href="#cb15-37" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f'  </span><span class="sc">{</span>name<span class="sc">:12}</span><span class="ss"> </span><span class="sc">{</span>s<span class="sc">.</span>iloc[<span class="op">-</span><span class="dv">1</span>] <span class="op">/</span> s<span class="sc">.</span>iloc[<span class="dv">0</span>]<span class="sc">:.2f}</span><span class="ss">x</span><span class="sc">{</span>note<span class="sc">}</span><span class="ss">'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="05_comparison_files/figure-html/cell-10-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Mean actual claim count by predicted-risk decile:
           GLM  XGBoost  Neural Net
decile                             
1       0.0321   0.0264      0.0294
2       0.0393   0.0317      0.0372
3       0.0485   0.0379      0.0402
4       0.0490   0.0375      0.0395
5       0.0498   0.0491      0.0457
6       0.0540   0.0468      0.0504
7       0.0519   0.0538      0.0535
8       0.0585   0.0516      0.0568
9       0.0648   0.0703      0.0649
10      0.0860   0.1288      0.1178

Top-to-bottom lift (riskiest group / safest group):
  GLM          2.68x
  XGBoost      4.88x
  Neural Net   4.01x</code></pre>
</div>
</div>
<section id="reading-the-discrimination-results" class="level3">
<h3 class="anchored" data-anchor-id="reading-the-discrimination-results">Reading the discrimination results</h3>
<p><strong>Frequency Gini:</strong> XGBoost leads clearly — 0.357 vs the GLM’s 0.266, a +34% relative improvement, matched by the lift chart (top-decile/bottom-decile ratio of 4.88x vs 2.68x). The Neural Net sits between the two on both measures (Gini 0.325, lift 4.01x). Unlike the severity race, this gap is real and reproduces outside a single split — treat it at face value rather than discounting it the way Appendix B’s severity result had to be discounted.</p>
<p><strong>Pure premium Gini follows the same ranking but compresses for the ML models</strong> (GLM 0.137, XGBoost 0.243, Neural Net 0.185): XGBoost’s frequency-driven ranking advantage carries through, but its collapsed severity predictions from Part 1 dilute how much of that advantage survives the multiplication into pure premium.</p>
<p><strong>The lift table has a discontinuity worth naming.</strong> Deciles 1–9 rise gradually and fairly evenly for all three models (roughly 0.03 → 0.06–0.07 actual claim rate), but decile 10 jumps sharply above decile 9 in every model (GLM 0.054 → 0.086, XGBoost 0.070 → 0.129, Neural Net 0.065 → 0.118). Most of each model’s discrimination is concentrated in isolating the riskiest ~10% of the book rather than fine ranking across the rest. Practically, this means a coarse “top-decile surcharge” captures most of the available signal regardless of which of these three models sets the tiers — the choice of model matters far more for <em>how large</em> that top tier’s premium should be than for <em>identifying</em> who belongs in it.</p>
</section>
</section>
<section id="part-4-interpretability-vs-accuracy" class="level2">
<h2 class="anchored" data-anchor-id="part-4-interpretability-vs-accuracy">Part 4: Interpretability vs Accuracy</h2>
<p>In an Australian APRA-regulated context, pricing models must be explainable. APRA’s Prudential Standard GPS 116 requires that premium rating factors are documented and defensible. This section evaluates each model’s regulatory viability alongside its predictive performance.</p>
<div id="interpretability-table" class="cell" data-execution_count="10">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Interpretability and regulatory risk are judgement calls, not measurements —</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="co"># they are the only hardcoded values here. Everything quantitative is loaded.</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>qualitative <span class="op">=</span> {</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">'GLM'</span>: {</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>        <span class="st">'Interpretability'</span>: <span class="st">'High'</span>,   <span class="st">'Regulatory risk'</span>: <span class="st">'Low'</span>,</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>        <span class="st">'Notes'</span>: <span class="st">'Coefficients directly auditable; multiplicative rating factors standard in industry'</span>,</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>    },</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">'XGBoost'</span>: {</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>        <span class="st">'Interpretability'</span>: <span class="st">'Medium'</span>, <span class="st">'Regulatory risk'</span>: <span class="st">'Medium'</span>,</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>        <span class="st">'Notes'</span>: <span class="st">'SHAP values provide local explanations; partial dependence shows learned relationships'</span>,</span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>    },</span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Neural Net'</span>: {</span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a>        <span class="st">'Interpretability'</span>: <span class="st">'Low'</span>,    <span class="st">'Regulatory risk'</span>: <span class="st">'High'</span>,</span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a>        <span class="st">'Notes'</span>: <span class="st">'Black-box; requires additional explanation tooling (SHAP, LIME) before regulatory submission'</span>,</span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a>    },</span>
<span id="cb17-16"><a href="#cb17-16" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb17-17"><a href="#cb17-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-18"><a href="#cb17-18" aria-hidden="true" tabindex="-1"></a>interp <span class="op">=</span> pd.DataFrame([</span>
<span id="cb17-19"><a href="#cb17-19" aria-hidden="true" tabindex="-1"></a>    {</span>
<span id="cb17-20"><a href="#cb17-20" aria-hidden="true" tabindex="-1"></a>        <span class="st">'Model'</span>:              m,</span>
<span id="cb17-21"><a href="#cb17-21" aria-hidden="true" tabindex="-1"></a>        <span class="st">'Frequency Deviance'</span>: metrics[m][<span class="st">'frequency'</span>][<span class="st">'PoissonDeviance'</span>],</span>
<span id="cb17-22"><a href="#cb17-22" aria-hidden="true" tabindex="-1"></a>        <span class="st">'Severity Deviance'</span>:  metrics[m][<span class="st">'severity'</span>][<span class="st">'GammaDeviance'</span>],</span>
<span id="cb17-23"><a href="#cb17-23" aria-hidden="true" tabindex="-1"></a>        <span class="st">'Freq Gini'</span>:          gini_results.loc[m, <span class="st">'Frequency Gini'</span>],</span>
<span id="cb17-24"><a href="#cb17-24" aria-hidden="true" tabindex="-1"></a>        <span class="st">'PP Gini'</span>:            gini_results.loc[m, <span class="st">'Pure Premium Gini'</span>],</span>
<span id="cb17-25"><a href="#cb17-25" aria-hidden="true" tabindex="-1"></a>        <span class="op">**</span>qualitative[m],</span>
<span id="cb17-26"><a href="#cb17-26" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb17-27"><a href="#cb17-27" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> m <span class="kw">in</span> MODELS</span>
<span id="cb17-28"><a href="#cb17-28" aria-hidden="true" tabindex="-1"></a>]).set_index(<span class="st">'Model'</span>)</span>
<span id="cb17-29"><a href="#cb17-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-30"><a href="#cb17-30" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(interp[[<span class="st">'Frequency Deviance'</span>, <span class="st">'Severity Deviance'</span>, <span class="st">'Freq Gini'</span>, <span class="st">'PP Gini'</span>,</span>
<span id="cb17-31"><a href="#cb17-31" aria-hidden="true" tabindex="-1"></a>              <span class="st">'Interpretability'</span>, <span class="st">'Regulatory risk'</span>]].<span class="bu">round</span>(<span class="dv">4</span>).to_string())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Frequency Deviance  Severity Deviance  Freq Gini  PP Gini Interpretability Regulatory risk
Model                                                                                                 
GLM                 43585.7326             1.0595     0.2660   0.1365             High             Low
XGBoost             41478.6442             1.3611     0.3565   0.2433           Medium          Medium
Neural Net          42250.4597             1.4114     0.3254   0.1853              Low            High</code></pre>
</div>
</div>
<div id="radar-chart" class="cell" data-execution_count="11">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Spider / radar chart: accuracy vs interpretability tradeoff</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Normalise each axis to [0, 1] with 1 = best. Deviances are lower-is-better, so</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="co"># they are inverted. Note this is a RELATIVE scale — the best model scores 1 on</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="co"># each axis by construction, so the chart shows ranking, not absolute quality.</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>freq_devs <span class="op">=</span> interp[<span class="st">'Frequency Deviance'</span>].values</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>sev_devs  <span class="op">=</span> interp[<span class="st">'Severity Deviance'</span>].values</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>interp_score <span class="op">=</span> np.array([<span class="fl">1.0</span>, <span class="fl">0.5</span>, <span class="fl">0.2</span>])  <span class="co"># subjective, matches the High/Medium/Low above</span></span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>reg_score    <span class="op">=</span> np.array([<span class="fl">1.0</span>, <span class="fl">0.6</span>, <span class="fl">0.2</span>])  <span class="co"># subjective</span></span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> invert_norm(v):</span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>    span <span class="op">=</span> v.<span class="bu">max</span>() <span class="op">-</span> v.<span class="bu">min</span>()</span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> np.ones_like(v) <span class="cf">if</span> span <span class="op">==</span> <span class="dv">0</span> <span class="cf">else</span> <span class="dv">1</span> <span class="op">-</span> (v <span class="op">-</span> v.<span class="bu">min</span>()) <span class="op">/</span> span</span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a>freq_norm <span class="op">=</span> invert_norm(freq_devs)</span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a>sev_norm  <span class="op">=</span> invert_norm(sev_devs)</span>
<span id="cb19-16"><a href="#cb19-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-17"><a href="#cb19-17" aria-hidden="true" tabindex="-1"></a>categories <span class="op">=</span> [<span class="st">'Freq</span><span class="ch">\n</span><span class="st">Deviance'</span>, <span class="st">'Sev</span><span class="ch">\n</span><span class="st">Deviance'</span>, <span class="st">'Interpretability'</span>, <span class="st">'Regulatory</span><span class="ch">\n</span><span class="st">Readiness'</span>]</span>
<span id="cb19-18"><a href="#cb19-18" aria-hidden="true" tabindex="-1"></a>N <span class="op">=</span> <span class="bu">len</span>(categories)</span>
<span id="cb19-19"><a href="#cb19-19" aria-hidden="true" tabindex="-1"></a>angles <span class="op">=</span> [n <span class="op">/</span> <span class="bu">float</span>(N) <span class="op">*</span> <span class="dv">2</span> <span class="op">*</span> np.pi <span class="cf">for</span> n <span class="kw">in</span> <span class="bu">range</span>(N)]</span>
<span id="cb19-20"><a href="#cb19-20" aria-hidden="true" tabindex="-1"></a>angles <span class="op">+=</span> angles[:<span class="dv">1</span>]</span>
<span id="cb19-21"><a href="#cb19-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-22"><a href="#cb19-22" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">7</span>, <span class="dv">7</span>), subplot_kw<span class="op">=</span>{<span class="st">'polar'</span>: <span class="va">True</span>})</span>
<span id="cb19-23"><a href="#cb19-23" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i, name <span class="kw">in</span> <span class="bu">enumerate</span>(MODELS):</span>
<span id="cb19-24"><a href="#cb19-24" aria-hidden="true" tabindex="-1"></a>    scores <span class="op">=</span> [freq_norm[i], sev_norm[i], interp_score[i], reg_score[i]]</span>
<span id="cb19-25"><a href="#cb19-25" aria-hidden="true" tabindex="-1"></a>    vals <span class="op">=</span> scores <span class="op">+</span> scores[:<span class="dv">1</span>]</span>
<span id="cb19-26"><a href="#cb19-26" aria-hidden="true" tabindex="-1"></a>    ax.plot(angles, vals, label<span class="op">=</span>name, color<span class="op">=</span>colors_map[name], linewidth<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb19-27"><a href="#cb19-27" aria-hidden="true" tabindex="-1"></a>    ax.fill(angles, vals, alpha<span class="op">=</span><span class="fl">0.1</span>, color<span class="op">=</span>colors_map[name])</span>
<span id="cb19-28"><a href="#cb19-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-29"><a href="#cb19-29" aria-hidden="true" tabindex="-1"></a>ax.set_xticks(angles[:<span class="op">-</span><span class="dv">1</span>])</span>
<span id="cb19-30"><a href="#cb19-30" aria-hidden="true" tabindex="-1"></a>ax.set_xticklabels(categories)</span>
<span id="cb19-31"><a href="#cb19-31" aria-hidden="true" tabindex="-1"></a>ax.set_ylim(<span class="dv">0</span>, <span class="dv">1</span>)</span>
<span id="cb19-32"><a href="#cb19-32" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">'Accuracy vs Interpretability Tradeoff'</span>, size<span class="op">=</span><span class="dv">13</span>, pad<span class="op">=</span><span class="dv">20</span>)</span>
<span id="cb19-33"><a href="#cb19-33" aria-hidden="true" tabindex="-1"></a>ax.legend(loc<span class="op">=</span><span class="st">'upper right'</span>, bbox_to_anchor<span class="op">=</span>(<span class="fl">1.3</span>, <span class="fl">1.1</span>))</span>
<span id="cb19-34"><a href="#cb19-34" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb19-35"><a href="#cb19-35" aria-hidden="true" tabindex="-1"></a>plt.savefig(<span class="st">'../results/23_radar_chart.png'</span>, dpi<span class="op">=</span><span class="dv">150</span>, bbox_inches<span class="op">=</span><span class="st">'tight'</span>)</span>
<span id="cb19-36"><a href="#cb19-36" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="05_comparison_files/figure-html/cell-12-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">Conclusion</h2>
<section id="model-recommendation" class="level3">
<h3 class="anchored" data-anchor-id="model-recommendation">Model recommendation</h3>
<p><strong>Frequency: recommend XGBoost.</strong> The Gini improvement (0.357 vs 0.266, +34% relative) and lift improvement (4.88x vs 2.68x) are large enough that “defer to interpretability when close” doesn’t apply here — this isn’t close. The honest recommendation is two-track: keep the GLM where full coefficient-level auditability is required today, and treat XGBoost (with SHAP-based local explanations) as the target once that explainability work is done, since the accuracy left on the table by staying with the GLM indefinitely is real.</p>
<p><strong>Severity: recommend the Gamma GLM, unambiguously.</strong> XGBoost and the Neural Net both fail to beat an intercept-only baseline (Gamma Deviance 1.36 and 1.41 vs ≈ 1.06 for predicting the mean for everyone); the GLM is the only one of the three that has extracted any real signal from the covariates. This isn’t a close call resolved by interpretability — it’s the only model of the three that works, and it matches the wider investigation in notebook 02’s Appendix B: six error distributions cluster within 0.03 percentage points of each other, a tuned gradient booster’s edge doesn’t survive cross-validation, and the severity ceiling here is a property of the data (near-zero premium information in claim size given these covariates), not of model class.</p>
<p><strong>Because severity dominates the pure premium multiplication and only the GLM is severity-sound, the practical recommendation is a hybrid</strong>: pair XGBoost’s frequency model with the GLM’s severity model, rather than reading the three “pure” columns compared above as the only options. That combination isn’t benchmarked directly above — it would need its own pure premium column to confirm — but it follows directly from treating frequency and severity as the separate decisions they are, which the metrics in Parts 1 and 3 support independently of each other.</p>
<p><strong>One number that doesn’t belong in a rate card yet:</strong> the pure premium EUR figures in Part 2 (all models, and the empirical benchmark) carry the frequency/severity join-gap inflation described there — roughly 27% of claim events have no matching cost record, and none of the models above correct for it. That’s a fix to make before any of these premium levels are quoted as absolute pricing, not a reason to revisit the model rankings above.</p>
</section>
<section id="regulatory-framing-apra-gps-116" class="level3">
<h3 class="anchored" data-anchor-id="regulatory-framing-apra-gps-116">Regulatory framing (APRA / GPS 116)</h3>
<p>Under APRA’s Prudential Standard GPS 116, premium rating factors must be documented and defensible. This is a property of the model class, not of this dataset’s results, so it holds regardless of what the rerun shows:</p>
<ul>
<li><strong>GLM:</strong> standard actuarial practice. With a log link, coefficients exponentiate directly into multiplicative rating factors — the form regulators and pricing actuaries already expect, with no additional explanation layer required.</li>
<li><strong>XGBoost:</strong> SHAP values and partial dependence plots make the model locally and globally interpretable, but that interpretation is a derived artefact, not the model itself — an extra layer of tooling and documentation a regulator has to be walked through, rather than a coefficient table they can read directly.</li>
<li><strong>Neural Net:</strong> the least defensible of the three without significant additional explainability work (SHAP, LIME, or similar), and the SHAP background/summary artefacts for it are not currently part of this notebook’s pipeline.</li>
</ul>
<p>None of this changes with the numbers above — a materially more accurate frequency model is still worth adopting, but adopting it means budgeting for the explainability work GPS 116 requires, not treating XGBoost’s Gini advantage as a free win.</p>


</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/dpark2380\.github\.io\/Insurance-Claims-Predictor\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>